// ======================================================================
// \title  DirectoryStatusEnumAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for DirectoryStatus enum
// ======================================================================

#ifndef Os_DirectoryStatusEnumAc_HPP
#define Os_DirectoryStatusEnumAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Os {

  //! FPP shadow-enum representing Os::Directory::Status
  class DirectoryStatus :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The serial representation type
      typedef U8 SerialType;

      //! The raw enum type
      enum T {
        //! Operation was successful
        OP_OK = 0,
        //! Directory doesn't exist
        DOESNT_EXIST = 1,
        //! No permission to read directory
        NO_PERMISSION = 2,
        //! Directory hasn't been opened yet
        NOT_OPENED = 3,
        //! Path is not a directory
        NOT_DIR = 4,
        //! Directory stream has no more files
        NO_MORE_FILES = 5,
        //! Directory has more files than can be read
        FILE_LIMIT = 6,
        //! Directory stream descriptor is invalid
        BAD_DESCRIPTOR = 7,
        //! Directory already exists
        ALREADY_EXISTS = 8,
        //! Operation is not supported by the current implementation
        NOT_SUPPORTED = 9,
        //! A catch-all for other errors. Have to look in implementation-specific code
        OTHER_ERROR = 10,
      };

      //! For backwards compatibility
      typedef T t;

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE = sizeof(SerialType),
        //! The number of enumerated constants
        NUM_CONSTANTS = 11,
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value of OP_OK)
      DirectoryStatus()
      {
        this->e = OP_OK;
      }

      //! Constructor (user-provided value)
      DirectoryStatus(
          const T e1 //!< The raw enum value
      )
      {
        this->e = e1;
      }

      //! Copy constructor
      DirectoryStatus(
          const DirectoryStatus& obj //!< The source object
      )
      {
        this->e = obj.e;
      }

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator (object)
      DirectoryStatus& operator=(
          const DirectoryStatus& obj //!< The source object
      );

      //! Copy assignment operator (raw enum)
      DirectoryStatus& operator=(
          T e1 //!< The enum value
      );

      //! Conversion operator
      operator T() const
      {
        return this->e;
      }

      //! Equality operator
      bool operator==(T e1) const
      {
        return this->e == e1;
      }

      //! Inequality operator
      bool operator!=(T e1) const
      {
        return !(*this == e1);
      }

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const DirectoryStatus& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Check raw enum value for validity
      bool isValid() const;

      //! Serialize raw enum value to SerialType
      Fw::SerializeStatus serializeTo(
          Fw::SerialBufferBase& buffer, //!< The serial buffer
          Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
      ) const;

      //! Deserialize raw enum value from SerialType
      Fw::SerializeStatus deserializeFrom(
          Fw::SerialBufferBase& buffer, //!< The serial buffer
          Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
      );

#if FW_SERIALIZABLE_TO_STRING

      //! Convert enum to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

    public:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The raw enum value
      T e;

  };

}

#endif
