// ======================================================================
// \title  DpSendPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DpSend port
// ======================================================================

#include "Fw/Dp/DpSendPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"

namespace Fw {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class DpSendPortBuffer : public Fw::LinearBufferBase {

      public:

        Fw::Serializable::SizeType getCapacity() const {
          return InputDpSendPort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputDpSendPort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputDpSendPort ::
    InputDpSendPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputDpSendPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputDpSendPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputDpSendPort ::
    invoke(
        FwDpIdType id,
        const Fw::Buffer& buffer
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, id, buffer);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputDpSendPort ::
    invokeSerial(Fw::LinearBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    FwDpIdType id;
    _status = _buffer.deserializeTo(id);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    Fw::Buffer buffer;
    _status = _buffer.deserializeTo(buffer);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, id, buffer);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputDpSendPort ::
    OutputDpSendPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputDpSendPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputDpSendPort ::
    addCallPort(InputDpSendPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputDpSendPort ::
    invoke(
        FwDpIdType id,
        const Fw::Buffer& buffer
    ) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(id, buffer);
    }
    else {
      Fw::SerializeStatus _status;
      DpSendPortBuffer _buffer;

      _status = _buffer.serializeFrom(id);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serializeFrom(buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(id, buffer);
#endif
  }

}
