// ======================================================================
// \title  TlmGetPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for TlmGet port
// ======================================================================

#include "Fw/Tlm/TlmGetPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"

namespace Fw {

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputTlmGetPort ::
    InputTlmGetPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputTlmGetPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputTlmGetPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  Fw::TlmValid InputTlmGetPort ::
    invoke(
        FwChanIdType id,
        Fw::Time& timeTag,
        Fw::TlmBuffer& val
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, id, timeTag, val);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputTlmGetPort ::
    invokeSerial(Fw::LinearBufferBase& _buffer)
  {
    // For ports with a return type, invokeSerial is not used
    (void) _buffer;

    FW_ASSERT(0);
    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputTlmGetPort ::
    OutputTlmGetPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputTlmGetPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputTlmGetPort ::
    addCallPort(InputTlmGetPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  Fw::TlmValid OutputTlmGetPort ::
    invoke(
        FwChanIdType id,
        Fw::Time& timeTag,
        Fw::TlmBuffer& val
    ) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_port != nullptr);
    return this->m_port->invoke(id, timeTag, val);
  }

}
