// ======================================================================
// \title  LinuxGpioDriverComponentAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for LinuxGpioDriver component base class
// ======================================================================

#ifndef Drv_LinuxGpioDriverComponentAc_HPP
#define Drv_LinuxGpioDriverComponentAc_HPP

#include <atomic>

#include "Drv/Ports/GpioReadPortAc.hpp"
#include "Drv/Ports/GpioWritePortAc.hpp"
#include "Fw/Comp/ActiveComponentBase.hpp"
#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Log/LogPortAc.hpp"
#include "Fw/Log/LogString.hpp"
#if FW_ENABLE_TEXT_LOGGING == 1
#include "Fw/Log/LogTextPortAc.hpp"
#endif
#include "Fw/Port/InputSerializePort.hpp"
#include "Fw/Port/OutputSerializePort.hpp"
#include "Fw/Time/TimePortAc.hpp"
#include "Os/Models/FileStatusEnumAc.hpp"
#include "Svc/Cycle/CyclePortAc.hpp"

namespace Drv {

  //! \class LinuxGpioDriverComponentBase
  //! \brief Auto-generated base for LinuxGpioDriver component
  class LinuxGpioDriverComponentBase :
    public Fw::PassiveComponentBase
  {

      // ----------------------------------------------------------------------
      // Friend classes
      // ----------------------------------------------------------------------

      //! Friend class tester to support autocoded test harness
      friend class LinuxGpioDriverTesterBase;
      //! Friend class tester implementation to support white-box testing
      friend class LinuxGpioDriverTester;

    protected:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      //! Enumerations for numbers of typed input ports
      enum {
        NUM_GPIOREAD_INPUT_PORTS = 1,
        NUM_GPIOWRITE_INPUT_PORTS = 1,
      };

      //! Enumerations for numbers of special output ports
      enum {
        NUM_LOG_OUTPUT_PORTS = 1,
        NUM_LOGTEXT_OUTPUT_PORTS = 1,
        NUM_TIME_OUTPUT_PORTS = 1,
      };

      //! Enumerations for numbers of typed output ports
      enum {
        NUM_GPIOINTERRUPT_OUTPUT_PORTS = 1,
      };

      //! Event IDs
      enum {
        EVENTID_OPENCHIP = 0x0,
        EVENTID_OPENCHIPERROR = 0x1,
        EVENTID_OPENPINERROR = 0x2,
        EVENTID_INTERRUPTREADERROR = 0x3,
        EVENTID_POLLINGERROR = 0x4,
      };

    public:

      // ----------------------------------------------------------------------
      // Component initialization
      // ----------------------------------------------------------------------

      //! Initialize LinuxGpioDriverComponentBase object
      void init(
          FwEnumStoreType instance = 0 //!< The instance number
      );

    public:

      // ----------------------------------------------------------------------
      // Getters for typed input ports
      // ----------------------------------------------------------------------

      //! Get typed input port at index
      //!
      //! \return gpioRead[portNum]
      Drv::InputGpioReadPort* get_gpioRead_InputPort(
          FwIndexType portNum //!< The port number
      );

      //! Get typed input port at index
      //!
      //! \return gpioWrite[portNum]
      Drv::InputGpioWritePort* get_gpioWrite_InputPort(
          FwIndexType portNum //!< The port number
      );

    public:

      // ----------------------------------------------------------------------
      // Connect input ports to special output ports
      // ----------------------------------------------------------------------

      //! Connect port to Log[portNum]
      void set_Log_OutputPort(
          FwIndexType portNum, //!< The port number
          Fw::InputLogPort* port //!< The input port
      );

#if FW_ENABLE_TEXT_LOGGING == 1

      //! Connect port to LogText[portNum]
      void set_LogText_OutputPort(
          FwIndexType portNum, //!< The port number
          Fw::InputLogTextPort* port //!< The input port
      );

#endif

      //! Connect port to Time[portNum]
      void set_Time_OutputPort(
          FwIndexType portNum, //!< The port number
          Fw::InputTimePort* port //!< The input port
      );

    public:

      // ----------------------------------------------------------------------
      // Connect typed input ports to typed output ports
      // ----------------------------------------------------------------------

      //! Connect port to gpioInterrupt[portNum]
      void set_gpioInterrupt_OutputPort(
          FwIndexType portNum, //!< The port number
          Svc::InputCyclePort* port //!< The input port
      );

#if FW_PORT_SERIALIZATION

    public:

      // ----------------------------------------------------------------------
      // Connect serial input ports to special output ports
      // ----------------------------------------------------------------------

      //! Connect port to Log[portNum]
      void set_Log_OutputPort(
          FwIndexType portNum, //!< The port number
          Fw::InputSerializePort* port //!< The port
      );

#if FW_ENABLE_TEXT_LOGGING == 1

      //! Connect port to LogText[portNum]
      void set_LogText_OutputPort(
          FwIndexType portNum, //!< The port number
          Fw::InputSerializePort* port //!< The port
      );

#endif

      //! Connect port to Time[portNum]
      void set_Time_OutputPort(
          FwIndexType portNum, //!< The port number
          Fw::InputSerializePort* port //!< The port
      );

#endif

#if FW_PORT_SERIALIZATION

    public:

      // ----------------------------------------------------------------------
      // Connect serial input ports to typed output ports
      // ----------------------------------------------------------------------

      //! Connect port to gpioInterrupt[portNum]
      void set_gpioInterrupt_OutputPort(
          FwIndexType portNum, //!< The port number
          Fw::InputSerializePort* port //!< The port
      );

#endif

    protected:

      // ----------------------------------------------------------------------
      // Component construction and destruction
      // ----------------------------------------------------------------------

      //! Construct LinuxGpioDriverComponentBase object
      LinuxGpioDriverComponentBase(
          const char* compName = "" //!< The component name
      );

      //! Destroy LinuxGpioDriverComponentBase object
      virtual ~LinuxGpioDriverComponentBase();

    protected:

      // ----------------------------------------------------------------------
      // Getters for numbers of typed input ports
      // ----------------------------------------------------------------------

      //! Get the number of gpioRead input ports
      //!
      //! \return The number of gpioRead input ports
      static constexpr FwIndexType getNum_gpioRead_InputPorts() {
        return NUM_GPIOREAD_INPUT_PORTS;
      }

      //! Get the number of gpioWrite input ports
      //!
      //! \return The number of gpioWrite input ports
      static constexpr FwIndexType getNum_gpioWrite_InputPorts() {
        return NUM_GPIOWRITE_INPUT_PORTS;
      }

    protected:

      // ----------------------------------------------------------------------
      // Getters for numbers of special output ports
      // ----------------------------------------------------------------------

      //! Get the number of Log output ports
      //!
      //! \return The number of Log output ports
      static constexpr FwIndexType getNum_Log_OutputPorts() {
        return NUM_LOG_OUTPUT_PORTS;
      }

#if FW_ENABLE_TEXT_LOGGING == 1

      //! Get the number of LogText output ports
      //!
      //! \return The number of LogText output ports
      static constexpr FwIndexType getNum_LogText_OutputPorts() {
        return NUM_LOGTEXT_OUTPUT_PORTS;
      }

#endif

      //! Get the number of Time output ports
      //!
      //! \return The number of Time output ports
      static constexpr FwIndexType getNum_Time_OutputPorts() {
        return NUM_TIME_OUTPUT_PORTS;
      }

    protected:

      // ----------------------------------------------------------------------
      // Getters for numbers of typed output ports
      // ----------------------------------------------------------------------

      //! Get the number of gpioInterrupt output ports
      //!
      //! \return The number of gpioInterrupt output ports
      static constexpr FwIndexType getNum_gpioInterrupt_OutputPorts() {
        return NUM_GPIOINTERRUPT_OUTPUT_PORTS;
      }

    protected:

      // ----------------------------------------------------------------------
      // Connection status queries for special output ports
      // ----------------------------------------------------------------------

      //! Check whether port Log is connected
      //!
      //! \return Whether port Log is connected
      bool isConnected_Log_OutputPort(
          FwIndexType portNum //!< The port number
      );

#if FW_ENABLE_TEXT_LOGGING == 1

      //! Check whether port LogText is connected
      //!
      //! \return Whether port LogText is connected
      bool isConnected_LogText_OutputPort(
          FwIndexType portNum //!< The port number
      );

#endif

      //! Check whether port Time is connected
      //!
      //! \return Whether port Time is connected
      bool isConnected_Time_OutputPort(
          FwIndexType portNum //!< The port number
      );

    protected:

      // ----------------------------------------------------------------------
      // Connection status queries for typed output ports
      // ----------------------------------------------------------------------

      //! Check whether port gpioInterrupt is connected
      //!
      //! \return Whether port gpioInterrupt is connected
      bool isConnected_gpioInterrupt_OutputPort(
          FwIndexType portNum //!< The port number
      );

    protected:

      // ----------------------------------------------------------------------
      // Handlers to implement for typed input ports
      // ----------------------------------------------------------------------

      //! Handler for input port gpioRead
      virtual Drv::GpioStatus gpioRead_handler(
          FwIndexType portNum, //!< The port number
          Fw::Logic& state
      ) = 0;

      //! Handler for input port gpioWrite
      virtual Drv::GpioStatus gpioWrite_handler(
          FwIndexType portNum, //!< The port number
          const Fw::Logic& state
      ) = 0;

    protected:

      // ----------------------------------------------------------------------
      // Port handler base-class functions for typed input ports
      //
      // Call these functions directly to bypass the corresponding ports
      // ----------------------------------------------------------------------

      //! Handler base-class function for input port gpioRead
      Drv::GpioStatus gpioRead_handlerBase(
          FwIndexType portNum, //!< The port number
          Fw::Logic& state
      );

      //! Handler base-class function for input port gpioWrite
      Drv::GpioStatus gpioWrite_handlerBase(
          FwIndexType portNum, //!< The port number
          const Fw::Logic& state
      );

    protected:

      // ----------------------------------------------------------------------
      // Invocation functions for typed output ports
      // ----------------------------------------------------------------------

      //! Invoke output port gpioInterrupt
      void gpioInterrupt_out(
          FwIndexType portNum, //!< The port number
          Os::RawTime& cycleStart //!< Cycle start timestamp
      );

    protected:

      // ----------------------------------------------------------------------
      // Event logging functions
      // ----------------------------------------------------------------------

      //! Log event OpenChip
      void log_DIAGNOSTIC_OpenChip(
          const Fw::StringBase& chip,
          const Fw::StringBase& chipLabel,
          U32 pin,
          const Fw::StringBase& pinMessage
      ) const;

      //! Log event OpenChipError
      void log_WARNING_HI_OpenChipError(
          const Fw::StringBase& chip,
          Os::FileStatus status
      ) const;

      //! Log event OpenPinError
      void log_WARNING_HI_OpenPinError(
          const Fw::StringBase& chip,
          U32 pin,
          const Fw::StringBase& pinMessage,
          Os::FileStatus status
      ) const;

      //! Log event InterruptReadError
      void log_WARNING_HI_InterruptReadError(
          U32 expected,
          U32 got
      ) const;

      //! Log event PollingError
      void log_WARNING_HI_PollingError(I32 error_number) const;

    protected:

      // ----------------------------------------------------------------------
      // Time
      // ----------------------------------------------------------------------

      //! Get the time
      //!
      //! \\return The current time
      Fw::Time getTime() const;

    private:

      // ----------------------------------------------------------------------
      // Calls for messages received on typed input ports
      // ----------------------------------------------------------------------

      //! Callback for port gpioRead
      static Drv::GpioStatus m_p_gpioRead_in(
          Fw::PassiveComponentBase* callComp, //!< The component instance
          FwIndexType portNum, //!< The port number
          Fw::Logic& state
      );

      //! Callback for port gpioWrite
      static Drv::GpioStatus m_p_gpioWrite_in(
          Fw::PassiveComponentBase* callComp, //!< The component instance
          FwIndexType portNum, //!< The port number
          const Fw::Logic& state
      );

    private:

      // ----------------------------------------------------------------------
      // Typed input ports
      // ----------------------------------------------------------------------

      //! Input port gpioRead
      Drv::InputGpioReadPort m_gpioRead_InputPort[NUM_GPIOREAD_INPUT_PORTS];

      //! Input port gpioWrite
      Drv::InputGpioWritePort m_gpioWrite_InputPort[NUM_GPIOWRITE_INPUT_PORTS];

    private:

      // ----------------------------------------------------------------------
      // Special output ports
      // ----------------------------------------------------------------------

      //! Output port Log
      Fw::OutputLogPort m_Log_OutputPort[NUM_LOG_OUTPUT_PORTS];

#if FW_ENABLE_TEXT_LOGGING == 1

      //! Output port LogText
      Fw::OutputLogTextPort m_LogText_OutputPort[NUM_LOGTEXT_OUTPUT_PORTS];

#endif

      //! Output port Time
      Fw::OutputTimePort m_Time_OutputPort[NUM_TIME_OUTPUT_PORTS];

    private:

      // ----------------------------------------------------------------------
      // Typed output ports
      // ----------------------------------------------------------------------

      //! Output port gpioInterrupt
      Svc::OutputCyclePort m_gpioInterrupt_OutputPort[NUM_GPIOINTERRUPT_OUTPUT_PORTS];

  };

}

#endif
