// ======================================================================
// \title  EnabledEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for Enabled enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "Fw/Types/EnabledEnumAc.hpp"

namespace Fw {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  Enabled& Enabled ::
    operator=(const Enabled& obj)
  {
    this->e = obj.e;
    return *this;
  }

  Enabled& Enabled ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const Enabled& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool Enabled ::
    isValid() const
  {
    return ((e >= DISABLED) && (e <= ENABLED));
  }

  Fw::SerializeStatus Enabled ::
    serializeTo(
        Fw::SerialBufferBase& buffer,
        Fw::Endianness mode
    ) const
  {
    const Fw::SerializeStatus status = buffer.serializeFrom(
        static_cast<SerialType>(this->e),
        mode
    );
    return status;
  }

  Fw::SerializeStatus Enabled ::
    deserializeFrom(
        Fw::SerialBufferBase& buffer,
        Fw::Endianness mode
    )
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserializeTo(es, mode);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void Enabled ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case DISABLED:
        s = "DISABLED";
        break;
      case ENABLED:
        s = "ENABLED";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIu8 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void Enabled ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIu8 "", e);
  }

#endif

}
