// ======================================================================
// \title  PlatformTaskIdTypeAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for PlatformTaskIdType alias
// ======================================================================

#ifndef PlatformTaskIdTypeAliasAc_HPP
#define PlatformTaskIdTypeAliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"

extern "C" {
#include "cmake/platform/unix/Platform/PlatformTaskIdTypeAliasAc.h"
}

#endif
