// ======================================================================
// \title  WatchDogPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for WatchDog port
// ======================================================================

#ifndef Svc_WatchDogPortAc_HPP
#define Svc_WatchDogPortAc_HPP

#include <cstdio>
#include <cstring>

#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Svc {

  //! Input WatchDog port
  //! Port for stroking a watchdog timer
  class InputWatchDogPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          sizeof(U32)
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef void (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        U32 code
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputWatchDogPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      void invoke(
          U32 code //!< Watchdog stroke code
      );

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::LinearBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output WatchDog port
  //! Port for stroking a watchdog timer
  class OutputWatchDogPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputWatchDogPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputWatchDogPort* callPort //!< The input port
      );

      //! Invoke a port interface
      void invoke(
          U32 code //!< Watchdog stroke code
      ) const;

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputWatchDogPort* m_port;

  };

}

#endif
