// ======================================================================
// \title  FwIdTypeAliasAc.h
// \author Generated by fpp-to-cpp
// \brief  h file for FwIdType alias
// ======================================================================

#ifndef FwIdTypeAliasAc_H
#define FwIdTypeAliasAc_H

#include "Fw/Types/BasicTypes.h"

//! The id type.
typedef U32 FwIdType;
#define PRI_FwIdType PRI_U32

#endif
