// ======================================================================
// \title  FwPrmIdTypeAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FwPrmIdType alias
// ======================================================================

#ifndef FwPrmIdTypeAliasAc_HPP
#define FwPrmIdTypeAliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"
#include "default/config/FwIdTypeAliasAc.hpp"

extern "C" {
#include "default/config/FwPrmIdTypeAliasAc.h"
}

#endif
