// ======================================================================
// \title  FwQueuePriorityTypeAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FwQueuePriorityType alias
// ======================================================================

#ifndef FwQueuePriorityTypeAliasAc_HPP
#define FwQueuePriorityTypeAliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"
#include "cmake/platform/unix/Platform/PlatformQueuePriorityTypeAliasAc.hpp"

extern "C" {
#include "default/config/FwQueuePriorityTypeAliasAc.h"
}

#endif
