// ======================================================================
// \title  FwTaskPriorityTypeAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FwTaskPriorityType alias
// ======================================================================

#ifndef FwTaskPriorityTypeAliasAc_HPP
#define FwTaskPriorityTypeAliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"
#include "cmake/platform/unix/Platform/PlatformTaskPriorityTypeAliasAc.hpp"

extern "C" {
#include "default/config/FwTaskPriorityTypeAliasAc.h"
}

#endif
