// ======================================================================
// \title  FwTimeContextStoreTypeAliasAc.h
// \author Generated by fpp-to-cpp
// \brief  h file for FwTimeContextStoreType alias
// ======================================================================

#ifndef FwTimeContextStoreTypeAliasAc_H
#define FwTimeContextStoreTypeAliasAc_H

#include "Fw/Types/BasicTypes.h"

//! The type used to serialize a time context value
typedef U8 FwTimeContextStoreType;
#define PRI_FwTimeContextStoreType PRI_U8

#endif
