// ======================================================================
// \title  FwTimeBaseStoreTypeAliasAc.h
// \author Generated by fpp-to-cpp
// \brief  h file for FwTimeBaseStoreType alias
// ======================================================================

#ifndef FwTimeBaseStoreTypeAliasAc_H
#define FwTimeBaseStoreTypeAliasAc_H

#include "Fw/Types/BasicTypes.h"

//! The type used to serialize a time base value
typedef U16 FwTimeBaseStoreType;
#define PRI_FwTimeBaseStoreType PRI_U16

#endif
