// ======================================================================
// \title  FwTlmPacketizeIdTypeAliasAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for FwTlmPacketizeIdType alias
// ======================================================================

#ifndef FwTlmPacketizeIdTypeAliasAc_HPP
#define FwTlmPacketizeIdTypeAliasAc_HPP

#include "Fw/Types/BasicTypes.hpp"

extern "C" {
#include "default/config/FwTlmPacketizeIdTypeAliasAc.h"
}

#endif
