// ======================================================================
// \title  TimeBaseEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for TimeBase enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "default/config/TimeBaseEnumAc.hpp"

// ----------------------------------------------------------------------
// Operators
// ----------------------------------------------------------------------

TimeBase& TimeBase ::
  operator=(const TimeBase& obj)
{
  this->e = obj.e;
  return *this;
}

TimeBase& TimeBase ::
  operator=(T e1)
{
  this->e = e1;
  return *this;
}

#ifdef BUILD_UT

std::ostream& operator<<(std::ostream& os, const TimeBase& obj) {
  Fw::String s;
  obj.toString(s);
  os << s;
  return os;
}

#endif

// ----------------------------------------------------------------------
// Member functions
// ----------------------------------------------------------------------

bool TimeBase ::
  isValid() const
{
  return ((e >= TB_NONE) && (e <= TB_SC_TIME))
    || ((e >= TB_DONT_CARE) && (e <= TB_DONT_CARE));
}

Fw::SerializeStatus TimeBase ::
  serializeTo(
      Fw::SerialBufferBase& buffer,
      Fw::Endianness mode
  ) const
{
  const Fw::SerializeStatus status = buffer.serializeFrom(
      static_cast<SerialType>(this->e),
      mode
  );
  return status;
}

Fw::SerializeStatus TimeBase ::
  deserializeFrom(
      Fw::SerialBufferBase& buffer,
      Fw::Endianness mode
  )
{
  SerialType es;
  Fw::SerializeStatus status = buffer.deserializeTo(es, mode);
  if (status == Fw::FW_SERIALIZE_OK) {
    this->e = static_cast<T>(es);
    if (!this->isValid()) {
      status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
    }
  }
  return status;
}

#if FW_SERIALIZABLE_TO_STRING

void TimeBase ::
  toString(Fw::StringBase& sb) const
{
  Fw::String s;
  switch (e) {
    case TB_NONE:
      s = "TB_NONE";
      break;
    case TB_PROC_TIME:
      s = "TB_PROC_TIME";
      break;
    case TB_WORKSTATION_TIME:
      s = "TB_WORKSTATION_TIME";
      break;
    case TB_SC_TIME:
      s = "TB_SC_TIME";
      break;
    case TB_DONT_CARE:
      s = "TB_DONT_CARE";
      break;
    default:
      s = "[invalid]";
      break;
  }
  sb.format("%s (%" PRIu16 ")", s.toChar(), e);
}

#elif FW_ENABLE_TEXT_LOGGING

void TimeBase ::
  toString(Fw::StringBase& sb) const
{
  sb.format("%" PRIu16 "", e);
}

#endif
