// ======================================================================
// \title  VersionEnumEnumAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for VersionEnum enum
// ======================================================================

#ifndef Svc_VersionCfg_VersionEnumEnumAc_HPP
#define Svc_VersionCfg_VersionEnumEnumAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Svc {

  namespace VersionCfg {

    //! Define a set of Version entries on a project-specific
    //! basis.
    class VersionEnum :
      public Fw::Serializable
    {

      public:

        // ----------------------------------------------------------------------
        // Types
        // ----------------------------------------------------------------------

        //! The serial representation type
        typedef U32 SerialType;

        //! The raw enum type
        enum T {
          //! Entry 0
          PROJECT_VERSION_00 = 0,
          //! Entry 1
          PROJECT_VERSION_01 = 1,
          //! Entry 2
          PROJECT_VERSION_02 = 2,
          //! Entry 3
          PROJECT_VERSION_03 = 3,
          //! Entry 4
          PROJECT_VERSION_04 = 4,
          //! Entry 5
          PROJECT_VERSION_05 = 5,
          //! Entry 6
          PROJECT_VERSION_06 = 6,
          //! Entry 7
          PROJECT_VERSION_07 = 7,
          //! Entry 8
          PROJECT_VERSION_08 = 8,
          //! Entry 9
          PROJECT_VERSION_09 = 9,
        };

        //! For backwards compatibility
        typedef T t;

      public:

        // ----------------------------------------------------------------------
        // Constants
        // ----------------------------------------------------------------------

        enum {
          //! The size of the serial representation
          SERIALIZED_SIZE = sizeof(SerialType),
          //! The number of enumerated constants
          NUM_CONSTANTS = 10,
        };

      public:

        // ----------------------------------------------------------------------
        // Constructors
        // ----------------------------------------------------------------------

        //! Constructor (default value of PROJECT_VERSION_00)
        VersionEnum()
        {
          this->e = PROJECT_VERSION_00;
        }

        //! Constructor (user-provided value)
        VersionEnum(
            const T e1 //!< The raw enum value
        )
        {
          this->e = e1;
        }

        //! Copy constructor
        VersionEnum(
            const VersionEnum& obj //!< The source object
        )
        {
          this->e = obj.e;
        }

      public:

        // ----------------------------------------------------------------------
        // Operators
        // ----------------------------------------------------------------------

        //! Copy assignment operator (object)
        VersionEnum& operator=(
            const VersionEnum& obj //!< The source object
        );

        //! Copy assignment operator (raw enum)
        VersionEnum& operator=(
            T e1 //!< The enum value
        );

        //! Conversion operator
        operator T() const
        {
          return this->e;
        }

        //! Equality operator
        bool operator==(T e1) const
        {
          return this->e == e1;
        }

        //! Inequality operator
        bool operator!=(T e1) const
        {
          return !(*this == e1);
        }

#ifdef BUILD_UT

        //! Ostream operator
        friend std::ostream& operator<<(
            std::ostream& os, //!< The ostream
            const VersionEnum& obj //!< The object
        );

#endif

      public:

        // ----------------------------------------------------------------------
        // Member functions
        // ----------------------------------------------------------------------

        //! Check raw enum value for validity
        bool isValid() const;

        //! Serialize raw enum value to SerialType
        Fw::SerializeStatus serializeTo(
            Fw::SerialBufferBase& buffer, //!< The serial buffer
            Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
        ) const;

        //! Deserialize raw enum value from SerialType
        Fw::SerializeStatus deserializeFrom(
            Fw::SerialBufferBase& buffer, //!< The serial buffer
            Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
        );

#if FW_SERIALIZABLE_TO_STRING

        //! Convert enum to string
        void toString(
            Fw::StringBase& sb //!< The StringBase object to hold the result
        ) const;

#endif

      public:

        // ----------------------------------------------------------------------
        // Member variables
        // ----------------------------------------------------------------------

        //! The raw enum value
        T e;

    };

  }

}

#endif
