// ======================================================================
// \title  OrbitSimDeploymentTopologyAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for OrbitSimDeployment topology
// ======================================================================

#include "OrbitSimDeployment/Top/OrbitSimDeploymentTopologyAc.hpp"

// ----------------------------------------------------------------------
// Component instances
// ----------------------------------------------------------------------

namespace CdhCore {

  Svc::CommandDispatcher cmdDisp(FW_OPTIONAL_NAME("cmdDisp"));

}

namespace CdhCore {

  Svc::EventManager events(FW_OPTIONAL_NAME("events"));

}

namespace CdhCore {

  Svc::AssertFatalAdapter fatalAdapter(FW_OPTIONAL_NAME("fatalAdapter"));

}

namespace CdhCore {

  Svc::FatalHandler fatalHandler(FW_OPTIONAL_NAME("fatalHandler"));

}

namespace CdhCore {

  Svc::Health health(FW_OPTIONAL_NAME("health"));

}

namespace CdhCore {

  Svc::PassiveTextLogger textLogger(FW_OPTIONAL_NAME("textLogger"));

}

namespace CdhCore {

  Svc::TlmChan tlmSend(FW_OPTIONAL_NAME("tlmSend"));

}

namespace CdhCore {

  Svc::Version version(FW_OPTIONAL_NAME("version"));

}

namespace ComCcsds {

  Svc::ComAggregator aggregator(FW_OPTIONAL_NAME("aggregator"));

}

namespace ComCcsds {

  Svc::Ccsds::ApidManager apidManager(FW_OPTIONAL_NAME("apidManager"));

}

namespace ComCcsds {

  Svc::ComQueue comQueue(FW_OPTIONAL_NAME("comQueue"));

}

namespace ComCcsds {

  Svc::ComStub comStub(FW_OPTIONAL_NAME("comStub"));

}

namespace ComCcsds {

  Svc::BufferManager commsBufferManager(FW_OPTIONAL_NAME("commsBufferManager"));

}

namespace ComCcsds {

  Svc::FprimeRouter fprimeRouter(FW_OPTIONAL_NAME("fprimeRouter"));

}

namespace ComCcsds {

  Svc::FrameAccumulator frameAccumulator(FW_OPTIONAL_NAME("frameAccumulator"));

}

namespace ComCcsds {

  Svc::Ccsds::TmFramer framer(FW_OPTIONAL_NAME("framer"));

}

namespace ComCcsds {

  Svc::Ccsds::SpacePacketDeframer spacePacketDeframer(FW_OPTIONAL_NAME("spacePacketDeframer"));

}

namespace ComCcsds {

  Svc::Ccsds::SpacePacketFramer spacePacketFramer(FW_OPTIONAL_NAME("spacePacketFramer"));

}

namespace ComCcsds {

  Svc::Ccsds::TcDeframer tcDeframer(FW_OPTIONAL_NAME("tcDeframer"));

}

namespace DataProducts {

  Svc::BufferManager dpBufferManager(FW_OPTIONAL_NAME("dpBufferManager"));

}

namespace DataProducts {

  Svc::DpCatalog dpCat(FW_OPTIONAL_NAME("dpCat"));

}

namespace DataProducts {

  Svc::DpManager dpMgr(FW_OPTIONAL_NAME("dpMgr"));

}

namespace DataProducts {

  Svc::DpWriter dpWriter(FW_OPTIONAL_NAME("dpWriter"));

}

namespace FileHandling {

  Svc::FileDownlink fileDownlink(FW_OPTIONAL_NAME("fileDownlink"));

}

namespace FileHandling {

  Svc::FileManager fileManager(FW_OPTIONAL_NAME("fileManager"));

}

namespace FileHandling {

  Svc::FileUplink fileUplink(FW_OPTIONAL_NAME("fileUplink"));

}

namespace FileHandling {

  Svc::PrmDb prmDb(FW_OPTIONAL_NAME("prmDb"));

}

namespace OrbitSimDeployment {

  Svc::ChronoTime chronoTime(FW_OPTIONAL_NAME("chronoTime"));

}

namespace OrbitSimDeployment {

  Svc::CmdSequencer cmdSeq(FW_OPTIONAL_NAME("cmdSeq"));

}

namespace OrbitSimDeployment {

  Drv::TcpServer comDriver(FW_OPTIONAL_NAME("comDriver"));

}

namespace OrbitSimDeployment {

  Components::MorseBlinker morseBlinker(FW_OPTIONAL_NAME("morseBlinker"));

}

namespace OrbitSimDeployment {

  Svc::ActiveRateGroup rateGroup1(FW_OPTIONAL_NAME("rateGroup1"));

}

namespace OrbitSimDeployment {

  Svc::ActiveRateGroup rateGroup2(FW_OPTIONAL_NAME("rateGroup2"));

}

namespace OrbitSimDeployment {

  Svc::ActiveRateGroup rateGroup3(FW_OPTIONAL_NAME("rateGroup3"));

}

namespace OrbitSimDeployment {

  Svc::RateGroupDriver rateGroupDriver(FW_OPTIONAL_NAME("rateGroupDriver"));

}

namespace OrbitSimDeployment {

  Svc::SystemResources systemResources(FW_OPTIONAL_NAME("systemResources"));

}

namespace OrbitSimDeployment {

  Svc::LinuxTimer timer(FW_OPTIONAL_NAME("timer"));

}

namespace OrbitSimDeployment {

  // ----------------------------------------------------------------------
  // Component configuration objects
  // ----------------------------------------------------------------------

  namespace ConfigObjects {

    namespace CdhCore_health {
      Svc::Health::PingEntry pingEntries[NUM_PING_ENTRIES] = {
        {
          PingEntries::CdhCore_cmdDisp::WARN,
          PingEntries::CdhCore_cmdDisp::FATAL,
          "CdhCore_cmdDisp"
        },
        {
          PingEntries::CdhCore_events::WARN,
          PingEntries::CdhCore_events::FATAL,
          "CdhCore_events"
        },
        {
          PingEntries::CdhCore_tlmSend::WARN,
          PingEntries::CdhCore_tlmSend::FATAL,
          "CdhCore_tlmSend"
        },
        {
          PingEntries::DataProducts_dpCat::WARN,
          PingEntries::DataProducts_dpCat::FATAL,
          "DataProducts_dpCat"
        },
        {
          PingEntries::FileHandling_fileDownlink::WARN,
          PingEntries::FileHandling_fileDownlink::FATAL,
          "FileHandling_fileDownlink"
        },
        {
          PingEntries::FileHandling_fileManager::WARN,
          PingEntries::FileHandling_fileManager::FATAL,
          "FileHandling_fileManager"
        },
        {
          PingEntries::FileHandling_fileUplink::WARN,
          PingEntries::FileHandling_fileUplink::FATAL,
          "FileHandling_fileUplink"
        },
        {
          PingEntries::FileHandling_prmDb::WARN,
          PingEntries::FileHandling_prmDb::FATAL,
          "FileHandling_prmDb"
        },
        {
          PingEntries::OrbitSimDeployment_cmdSeq::WARN,
          PingEntries::OrbitSimDeployment_cmdSeq::FATAL,
          "OrbitSimDeployment_cmdSeq"
        },
        {
          PingEntries::OrbitSimDeployment_rateGroup1::WARN,
          PingEntries::OrbitSimDeployment_rateGroup1::FATAL,
          "OrbitSimDeployment_rateGroup1"
        },
        {
          PingEntries::OrbitSimDeployment_rateGroup2::WARN,
          PingEntries::OrbitSimDeployment_rateGroup2::FATAL,
          "OrbitSimDeployment_rateGroup2"
        },
        {
          PingEntries::OrbitSimDeployment_rateGroup3::WARN,
          PingEntries::OrbitSimDeployment_rateGroup3::FATAL,
          "OrbitSimDeployment_rateGroup3"
        },
      };
    }

    namespace ComCcsds_commsBufferManager {
      Svc::BufferManager::BufferBins bins;
    }

    namespace ComCcsds_frameAccumulator {
      Svc::FrameDetectors::CcsdsTcFrameDetector frameDetector;
    }

    namespace DataProducts_dpBufferManager {
      Svc::BufferManager::BufferBins bins;
    }

  }

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void initComponents(const TopologyState& state) {
    CdhCore::cmdDisp.init(QueueSizes::CdhCore_cmdDisp, InstanceIds::CdhCore_cmdDisp);
    CdhCore::events.init(QueueSizes::CdhCore_events, InstanceIds::CdhCore_events);
    CdhCore::fatalAdapter.init(InstanceIds::CdhCore_fatalAdapter);
    CdhCore::fatalHandler.init(InstanceIds::CdhCore_fatalHandler);
    CdhCore::health.init(QueueSizes::CdhCore_health, InstanceIds::CdhCore_health);
    CdhCore::textLogger.init(InstanceIds::CdhCore_textLogger);
    CdhCore::tlmSend.init(QueueSizes::CdhCore_tlmSend, InstanceIds::CdhCore_tlmSend);
    CdhCore::version.init(InstanceIds::CdhCore_version);
    ComCcsds::aggregator.init(QueueSizes::ComCcsds_aggregator, InstanceIds::ComCcsds_aggregator);
    ComCcsds::apidManager.init(InstanceIds::ComCcsds_apidManager);
    ComCcsds::comQueue.init(QueueSizes::ComCcsds_comQueue, InstanceIds::ComCcsds_comQueue);
    ComCcsds::comStub.init(InstanceIds::ComCcsds_comStub);
    ComCcsds::commsBufferManager.init(InstanceIds::ComCcsds_commsBufferManager);
    ComCcsds::fprimeRouter.init(InstanceIds::ComCcsds_fprimeRouter);
    ComCcsds::frameAccumulator.init(InstanceIds::ComCcsds_frameAccumulator);
    ComCcsds::framer.init(InstanceIds::ComCcsds_framer);
    ComCcsds::spacePacketDeframer.init(InstanceIds::ComCcsds_spacePacketDeframer);
    ComCcsds::spacePacketFramer.init(InstanceIds::ComCcsds_spacePacketFramer);
    ComCcsds::tcDeframer.init(InstanceIds::ComCcsds_tcDeframer);
    DataProducts::dpBufferManager.init(InstanceIds::DataProducts_dpBufferManager);
    DataProducts::dpCat.init(QueueSizes::DataProducts_dpCat, InstanceIds::DataProducts_dpCat);
    DataProducts::dpMgr.init(QueueSizes::DataProducts_dpMgr, InstanceIds::DataProducts_dpMgr);
    DataProducts::dpWriter.init(QueueSizes::DataProducts_dpWriter, InstanceIds::DataProducts_dpWriter);
    FileHandling::fileDownlink.init(QueueSizes::FileHandling_fileDownlink, InstanceIds::FileHandling_fileDownlink);
    FileHandling::fileManager.init(QueueSizes::FileHandling_fileManager, InstanceIds::FileHandling_fileManager);
    FileHandling::fileUplink.init(QueueSizes::FileHandling_fileUplink, InstanceIds::FileHandling_fileUplink);
    FileHandling::prmDb.init(QueueSizes::FileHandling_prmDb, InstanceIds::FileHandling_prmDb);
    OrbitSimDeployment::chronoTime.init(InstanceIds::OrbitSimDeployment_chronoTime);
    OrbitSimDeployment::cmdSeq.init(QueueSizes::OrbitSimDeployment_cmdSeq, InstanceIds::OrbitSimDeployment_cmdSeq);
    OrbitSimDeployment::comDriver.init(InstanceIds::OrbitSimDeployment_comDriver);
    OrbitSimDeployment::morseBlinker.init(QueueSizes::OrbitSimDeployment_morseBlinker, InstanceIds::OrbitSimDeployment_morseBlinker);
    OrbitSimDeployment::rateGroup1.init(QueueSizes::OrbitSimDeployment_rateGroup1, InstanceIds::OrbitSimDeployment_rateGroup1);
    OrbitSimDeployment::rateGroup2.init(QueueSizes::OrbitSimDeployment_rateGroup2, InstanceIds::OrbitSimDeployment_rateGroup2);
    OrbitSimDeployment::rateGroup3.init(QueueSizes::OrbitSimDeployment_rateGroup3, InstanceIds::OrbitSimDeployment_rateGroup3);
    OrbitSimDeployment::rateGroupDriver.init(InstanceIds::OrbitSimDeployment_rateGroupDriver);
    OrbitSimDeployment::systemResources.init(InstanceIds::OrbitSimDeployment_systemResources);
    OrbitSimDeployment::timer.init(InstanceIds::OrbitSimDeployment_timer);
  }

  void configComponents(const TopologyState& state) {
    // Health is supplied a set of ping entires.
    CdhCore::health.setPingEntries(
        ConfigObjects::CdhCore_health::pingEntries,
        FW_NUM_ARRAY_ELEMENTS(ConfigObjects::CdhCore_health::pingEntries),
        ConfigConstants::CdhCore_health::HEALTH_WATCHDOG_CODE
    );
    // Startup TLM and Config verbosity for Versions
    CdhCore::version.config(true);
    using namespace ComCcsds;
    Svc::ComQueue::QueueConfigurationTable configurationTable;

    // Events (highest-priority)
    configurationTable.entries[Ports_ComPacketQueue::EVENTS].depth = ComCcsdsConfig::QueueDepths::events;
    configurationTable.entries[Ports_ComPacketQueue::EVENTS].priority = ComCcsdsConfig::QueuePriorities::events;

    // Telemetry
    configurationTable.entries[Ports_ComPacketQueue::TELEMETRY].depth = ComCcsdsConfig::QueueDepths::tlm;
    configurationTable.entries[Ports_ComPacketQueue::TELEMETRY].priority = ComCcsdsConfig::QueuePriorities::tlm;

    // File Downlink Queue (buffer queue using NUM_CONSTANTS offset)
    configurationTable.entries[Ports_ComPacketQueue::NUM_CONSTANTS + Ports_ComBufferQueue::FILE].depth = ComCcsdsConfig::QueueDepths::file;
    configurationTable.entries[Ports_ComPacketQueue::NUM_CONSTANTS + Ports_ComBufferQueue::FILE].priority = ComCcsdsConfig::QueuePriorities::file;

    // Allocation identifier is 0 as the MallocAllocator discards it
    ComCcsds::comQueue.configure(configurationTable, 0, ComCcsds::Allocation::memAllocator);
    memset(&ConfigObjects::ComCcsds_commsBufferManager::bins, 0, sizeof(ConfigObjects::ComCcsds_commsBufferManager::bins));
    ConfigObjects::ComCcsds_commsBufferManager::bins.bins[0].bufferSize = ComCcsdsConfig::BuffMgr::commsBuffSize;
    ConfigObjects::ComCcsds_commsBufferManager::bins.bins[0].numBuffers = ComCcsdsConfig::BuffMgr::commsBuffCount;
    ConfigObjects::ComCcsds_commsBufferManager::bins.bins[1].bufferSize = ComCcsdsConfig::BuffMgr::commsFileBuffSize;
    ConfigObjects::ComCcsds_commsBufferManager::bins.bins[1].numBuffers = ComCcsdsConfig::BuffMgr::commsFileBuffCount;
    ComCcsds::commsBufferManager.setup(
        ComCcsdsConfig::BuffMgr::commsBuffMgrId,
        0,
        ComCcsds::Allocation::memAllocator,
        ConfigObjects::ComCcsds_commsBufferManager::bins
    );
    ComCcsds::frameAccumulator.configure(
        ConfigObjects::ComCcsds_frameAccumulator::frameDetector,
        1,
        ComCcsds::Allocation::memAllocator,
        ComCcsdsConfig::BuffMgr::frameAccumulatorSize
    );
    memset(&ConfigObjects::DataProducts_dpBufferManager::bins, 0, sizeof(ConfigObjects::DataProducts_dpBufferManager::bins));
    ConfigObjects::DataProducts_dpBufferManager::bins.bins[0].bufferSize = DataProductsConfig::BuffMgr::dpBufferStoreSize;
    ConfigObjects::DataProducts_dpBufferManager::bins.bins[0].numBuffers = DataProductsConfig::BuffMgr::dpBufferStoreCount;
    DataProducts::dpBufferManager.setup(
        DataProductsConfig::BuffMgr::dpBufferManagerId,
        0,
        DataProducts::Allocation::memAllocator,
        ConfigObjects::DataProducts_dpBufferManager::bins
    );
    Fw::FileNameString dpDir(DataProductsConfig::Paths::dpDir);
    Fw::FileNameString dpState(DataProductsConfig::Paths::dpState);
    Os::FileSystem::createDirectory(dpDir.toChar());
    DataProducts::dpCat.configure(&dpDir,1,dpState,0, DataProducts::Allocation::memAllocator);
    DataProducts::dpWriter.configure(dpDir);
    FileHandling::fileDownlink.configure(
        FileHandlingConfig::DownlinkConfig::timeout,
        FileHandlingConfig::DownlinkConfig::cooldown,
        FileHandlingConfig::DownlinkConfig::cycleTime,
        FileHandlingConfig::DownlinkConfig::fileQueueDepth
    );
    FileHandling::prmDb.configure("PrmDb.dat");
  }

  void setBaseIds() {
    OrbitSimDeployment::morseBlinker.setIdBase(BaseIds::OrbitSimDeployment_morseBlinker);
    CdhCore::cmdDisp.setIdBase(BaseIds::CdhCore_cmdDisp);
    CdhCore::events.setIdBase(BaseIds::CdhCore_events);
    CdhCore::health.setIdBase(BaseIds::CdhCore_health);
    CdhCore::version.setIdBase(BaseIds::CdhCore_version);
    CdhCore::textLogger.setIdBase(BaseIds::CdhCore_textLogger);
    CdhCore::fatalAdapter.setIdBase(BaseIds::CdhCore_fatalAdapter);
    CdhCore::tlmSend.setIdBase(BaseIds::CdhCore_tlmSend);
    CdhCore::fatalHandler.setIdBase(BaseIds::CdhCore_fatalHandler);
    ComCcsds::comQueue.setIdBase(BaseIds::ComCcsds_comQueue);
    ComCcsds::frameAccumulator.setIdBase(BaseIds::ComCcsds_frameAccumulator);
    ComCcsds::commsBufferManager.setIdBase(BaseIds::ComCcsds_commsBufferManager);
    ComCcsds::fprimeRouter.setIdBase(BaseIds::ComCcsds_fprimeRouter);
    ComCcsds::tcDeframer.setIdBase(BaseIds::ComCcsds_tcDeframer);
    ComCcsds::spacePacketDeframer.setIdBase(BaseIds::ComCcsds_spacePacketDeframer);
    ComCcsds::aggregator.setIdBase(BaseIds::ComCcsds_aggregator);
    ComCcsds::framer.setIdBase(BaseIds::ComCcsds_framer);
    ComCcsds::spacePacketFramer.setIdBase(BaseIds::ComCcsds_spacePacketFramer);
    ComCcsds::apidManager.setIdBase(BaseIds::ComCcsds_apidManager);
    ComCcsds::comStub.setIdBase(BaseIds::ComCcsds_comStub);
    DataProducts::dpCat.setIdBase(BaseIds::DataProducts_dpCat);
    DataProducts::dpMgr.setIdBase(BaseIds::DataProducts_dpMgr);
    DataProducts::dpWriter.setIdBase(BaseIds::DataProducts_dpWriter);
    DataProducts::dpBufferManager.setIdBase(BaseIds::DataProducts_dpBufferManager);
    FileHandling::fileUplink.setIdBase(BaseIds::FileHandling_fileUplink);
    FileHandling::fileDownlink.setIdBase(BaseIds::FileHandling_fileDownlink);
    FileHandling::fileManager.setIdBase(BaseIds::FileHandling_fileManager);
    FileHandling::prmDb.setIdBase(BaseIds::FileHandling_prmDb);
    OrbitSimDeployment::rateGroup1.setIdBase(BaseIds::OrbitSimDeployment_rateGroup1);
    OrbitSimDeployment::rateGroup2.setIdBase(BaseIds::OrbitSimDeployment_rateGroup2);
    OrbitSimDeployment::rateGroup3.setIdBase(BaseIds::OrbitSimDeployment_rateGroup3);
    OrbitSimDeployment::cmdSeq.setIdBase(BaseIds::OrbitSimDeployment_cmdSeq);
    OrbitSimDeployment::chronoTime.setIdBase(BaseIds::OrbitSimDeployment_chronoTime);
    OrbitSimDeployment::rateGroupDriver.setIdBase(BaseIds::OrbitSimDeployment_rateGroupDriver);
    OrbitSimDeployment::systemResources.setIdBase(BaseIds::OrbitSimDeployment_systemResources);
    OrbitSimDeployment::timer.setIdBase(BaseIds::OrbitSimDeployment_timer);
    OrbitSimDeployment::comDriver.setIdBase(BaseIds::OrbitSimDeployment_comDriver);
  }

  void connectComponents() {

    // CdhCore_cmdSeq
    CdhCore::cmdDisp.set_seqCmdStatus_OutputPort(
        1,
        OrbitSimDeployment::cmdSeq.get_cmdResponseIn_InputPort(0)
    );
    OrbitSimDeployment::cmdSeq.set_comCmdOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_seqCmdBuff_InputPort(1)
    );

    // ComCcsds_CdhCore
    CdhCore::cmdDisp.set_seqCmdStatus_OutputPort(
        0,
        ComCcsds::fprimeRouter.get_cmdResponseIn_InputPort(0)
    );
    CdhCore::events.set_PktSend_OutputPort(
        0,
        ComCcsds::comQueue.get_comPacketQueueIn_InputPort(0)
    );
    CdhCore::tlmSend.set_PktSend_OutputPort(
        0,
        ComCcsds::comQueue.get_comPacketQueueIn_InputPort(1)
    );
    ComCcsds::fprimeRouter.set_commandOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_seqCmdBuff_InputPort(0)
    );

    // ComCcsds_FileHandling
    ComCcsds::comQueue.set_bufferReturnOut_OutputPort(
        0,
        FileHandling::fileDownlink.get_bufferReturn_InputPort(0)
    );
    ComCcsds::fprimeRouter.set_fileOut_OutputPort(
        0,
        FileHandling::fileUplink.get_bufferSendIn_InputPort(0)
    );
    FileHandling::fileDownlink.set_bufferSendOut_OutputPort(
        0,
        ComCcsds::comQueue.get_bufferQueueIn_InputPort(0)
    );
    FileHandling::fileUplink.set_bufferSendOut_OutputPort(
        0,
        ComCcsds::fprimeRouter.get_fileBufferReturnIn_InputPort(0)
    );

    // ComStub
    ComCcsds::comStub.set_comStatusOut_OutputPort(
        0,
        ComCcsds::framer.get_comStatusIn_InputPort(0)
    );
    ComCcsds::comStub.set_dataOut_OutputPort(
        0,
        ComCcsds::frameAccumulator.get_dataIn_InputPort(0)
    );
    ComCcsds::comStub.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::framer.get_dataReturnIn_InputPort(0)
    );
    ComCcsds::frameAccumulator.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::comStub.get_dataReturnIn_InputPort(0)
    );
    ComCcsds::framer.set_dataOut_OutputPort(
        0,
        ComCcsds::comStub.get_dataIn_InputPort(0)
    );

    // Command
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        0,
        CdhCore::cmdDisp.get_CmdDisp_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        1,
        CdhCore::events.get_CmdDisp_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        2,
        CdhCore::health.get_CmdDisp_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        3,
        CdhCore::version.get_cmdIn_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        4,
        DataProducts::dpCat.get_CmdDisp_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        5,
        DataProducts::dpMgr.get_cmdIn_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        6,
        DataProducts::dpWriter.get_cmdIn_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        7,
        FileHandling::fileDownlink.get_cmdIn_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        8,
        FileHandling::fileManager.get_cmdIn_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        9,
        FileHandling::prmDb.get_CmdDisp_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        10,
        OrbitSimDeployment::cmdSeq.get_cmdIn_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        11,
        OrbitSimDeployment::morseBlinker.get_cmdIn_InputPort(0)
    );
    CdhCore::cmdDisp.set_compCmdSend_OutputPort(
        12,
        OrbitSimDeployment::systemResources.get_CmdDisp_InputPort(0)
    );

    // CommandRegistration
    CdhCore::cmdDisp.set_CmdReg_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(0)
    );
    CdhCore::events.set_CmdReg_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(1)
    );
    CdhCore::health.set_CmdReg_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(2)
    );
    CdhCore::version.set_cmdRegOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(3)
    );
    DataProducts::dpCat.set_CmdReg_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(4)
    );
    DataProducts::dpMgr.set_cmdRegIn_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(5)
    );
    DataProducts::dpWriter.set_cmdRegIn_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(6)
    );
    FileHandling::fileDownlink.set_cmdRegOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(7)
    );
    FileHandling::fileManager.set_cmdRegOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(8)
    );
    FileHandling::prmDb.set_CmdReg_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(9)
    );
    OrbitSimDeployment::cmdSeq.set_cmdRegOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(10)
    );
    OrbitSimDeployment::morseBlinker.set_cmdRegOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(11)
    );
    OrbitSimDeployment::systemResources.set_CmdReg_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdReg_InputPort(12)
    );

    // CommandResponse
    CdhCore::cmdDisp.set_CmdStatus_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    CdhCore::events.set_CmdStatus_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    CdhCore::health.set_CmdStatus_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    CdhCore::version.set_cmdResponseOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    DataProducts::dpCat.set_CmdStatus_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    DataProducts::dpMgr.set_cmdResponseOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    DataProducts::dpWriter.set_cmdResponseOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    FileHandling::fileDownlink.set_cmdResponseOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    FileHandling::fileManager.set_cmdResponseOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    FileHandling::prmDb.set_CmdStatus_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    OrbitSimDeployment::cmdSeq.set_cmdResponseOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    OrbitSimDeployment::morseBlinker.set_cmdResponseOut_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );
    OrbitSimDeployment::systemResources.set_CmdStatus_OutputPort(
        0,
        CdhCore::cmdDisp.get_compCmdStat_InputPort(0)
    );

    // Communications
    ComCcsds::comStub.set_drvReceiveReturnOut_OutputPort(
        0,
        OrbitSimDeployment::comDriver.get_recvReturnIn_InputPort(0)
    );
    ComCcsds::comStub.set_drvSendOut_OutputPort(
        0,
        OrbitSimDeployment::comDriver.get_send_InputPort(0)
    );
    OrbitSimDeployment::comDriver.set_allocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferGetCallee_InputPort(0)
    );
    OrbitSimDeployment::comDriver.set_deallocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferSendIn_InputPort(0)
    );
    OrbitSimDeployment::comDriver.set_ready_OutputPort(
        0,
        ComCcsds::comStub.get_drvConnected_InputPort(0)
    );
    OrbitSimDeployment::comDriver.set_recv_OutputPort(
        0,
        ComCcsds::comStub.get_drvReceiveIn_InputPort(0)
    );

    // DataProducts
    DataProducts::dpMgr.set_bufferGetOut_OutputPort(
        0,
        DataProducts::dpBufferManager.get_bufferGetCallee_InputPort(0)
    );
    DataProducts::dpMgr.set_productSendOut_OutputPort(
        0,
        DataProducts::dpWriter.get_bufferSendIn_InputPort(0)
    );
    DataProducts::dpWriter.set_deallocBufferSendOut_OutputPort(
        0,
        DataProducts::dpBufferManager.get_bufferSendIn_InputPort(0)
    );

    // Downlink
    ComCcsds::aggregator.set_comStatusOut_OutputPort(
        0,
        ComCcsds::spacePacketFramer.get_comStatusIn_InputPort(0)
    );
    ComCcsds::aggregator.set_dataOut_OutputPort(
        0,
        ComCcsds::framer.get_dataIn_InputPort(0)
    );
    ComCcsds::aggregator.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::spacePacketFramer.get_dataReturnIn_InputPort(0)
    );
    ComCcsds::comQueue.set_dataOut_OutputPort(
        0,
        ComCcsds::spacePacketFramer.get_dataIn_InputPort(0)
    );
    ComCcsds::framer.set_comStatusOut_OutputPort(
        0,
        ComCcsds::aggregator.get_comStatusIn_InputPort(0)
    );
    ComCcsds::framer.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::aggregator.get_dataReturnIn_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_bufferAllocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferGetCallee_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_bufferDeallocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferSendIn_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_comStatusOut_OutputPort(
        0,
        ComCcsds::comQueue.get_comStatusIn_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_dataOut_OutputPort(
        0,
        ComCcsds::aggregator.get_dataIn_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::comQueue.get_dataReturnIn_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_getApidSeqCount_OutputPort(
        0,
        ComCcsds::apidManager.get_getApidSeqCountIn_InputPort(0)
    );

    // Events
    CdhCore::cmdDisp.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    CdhCore::events.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    CdhCore::fatalAdapter.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    CdhCore::health.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    CdhCore::version.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::apidManager.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::comQueue.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::commsBufferManager.set_eventOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::fprimeRouter.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::frameAccumulator.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::framer.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    ComCcsds::tcDeframer.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    DataProducts::dpBufferManager.set_eventOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    DataProducts::dpCat.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    DataProducts::dpMgr.set_eventOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    DataProducts::dpWriter.set_eventOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    FileHandling::fileDownlink.set_eventOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    FileHandling::fileManager.set_eventOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    FileHandling::fileUplink.set_eventOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    FileHandling::prmDb.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    OrbitSimDeployment::cmdSeq.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    OrbitSimDeployment::morseBlinker.set_logOut_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    OrbitSimDeployment::rateGroup1.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    OrbitSimDeployment::rateGroup2.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );
    OrbitSimDeployment::systemResources.set_Log_OutputPort(
        0,
        CdhCore::events.get_LogRecv_InputPort(0)
    );

    // FaultProtection
    CdhCore::events.set_FatalAnnounce_OutputPort(
        0,
        CdhCore::fatalHandler.get_FatalReceive_InputPort(0)
    );

    // FileHandling_DataProducts
    DataProducts::dpCat.set_fileOut_OutputPort(
        0,
        FileHandling::fileDownlink.get_SendFile_InputPort(0)
    );
    FileHandling::fileDownlink.set_FileComplete_OutputPort(
        0,
        DataProducts::dpCat.get_fileDone_InputPort(0)
    );

    // Health
    CdhCore::cmdDisp.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(0)
    );
    CdhCore::events.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(1)
    );
    CdhCore::health.set_PingSend_OutputPort(
        0,
        CdhCore::cmdDisp.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        1,
        CdhCore::events.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        2,
        CdhCore::tlmSend.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        3,
        DataProducts::dpCat.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        4,
        FileHandling::fileDownlink.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        5,
        FileHandling::fileManager.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        6,
        FileHandling::fileUplink.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        7,
        FileHandling::prmDb.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        8,
        OrbitSimDeployment::cmdSeq.get_pingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        9,
        OrbitSimDeployment::rateGroup1.get_PingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        10,
        OrbitSimDeployment::rateGroup2.get_PingIn_InputPort(0)
    );
    CdhCore::health.set_PingSend_OutputPort(
        11,
        OrbitSimDeployment::rateGroup3.get_PingIn_InputPort(0)
    );
    CdhCore::tlmSend.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(2)
    );
    DataProducts::dpCat.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(3)
    );
    FileHandling::fileDownlink.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(4)
    );
    FileHandling::fileManager.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(5)
    );
    FileHandling::fileUplink.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(6)
    );
    FileHandling::prmDb.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(7)
    );
    OrbitSimDeployment::cmdSeq.set_pingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(8)
    );
    OrbitSimDeployment::rateGroup1.set_PingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(9)
    );
    OrbitSimDeployment::rateGroup2.set_PingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(10)
    );
    OrbitSimDeployment::rateGroup3.set_PingOut_OutputPort(
        0,
        CdhCore::health.get_PingReturn_InputPort(11)
    );

    // Parameters
    ComCcsds::framer.set_prmGetOut_OutputPort(
        0,
        FileHandling::prmDb.get_getPrm_InputPort(0)
    );
    ComCcsds::framer.set_prmSetOut_OutputPort(
        0,
        FileHandling::prmDb.get_setPrm_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_prmGetOut_OutputPort(
        0,
        FileHandling::prmDb.get_getPrm_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_prmSetOut_OutputPort(
        0,
        FileHandling::prmDb.get_setPrm_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_prmGetOut_OutputPort(
        0,
        FileHandling::prmDb.get_getPrm_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_prmSetOut_OutputPort(
        0,
        FileHandling::prmDb.get_setPrm_InputPort(0)
    );
    ComCcsds::tcDeframer.set_prmGetOut_OutputPort(
        0,
        FileHandling::prmDb.get_getPrm_InputPort(0)
    );
    ComCcsds::tcDeframer.set_prmSetOut_OutputPort(
        0,
        FileHandling::prmDb.get_setPrm_InputPort(0)
    );

    // RateGroups
    OrbitSimDeployment::rateGroup1.set_RateGroupMemberOut_OutputPort(
        0,
        CdhCore::tlmSend.get_Run_InputPort(0)
    );
    OrbitSimDeployment::rateGroup1.set_RateGroupMemberOut_OutputPort(
        1,
        FileHandling::fileDownlink.get_Run_InputPort(0)
    );
    OrbitSimDeployment::rateGroup1.set_RateGroupMemberOut_OutputPort(
        2,
        OrbitSimDeployment::systemResources.get_run_InputPort(0)
    );
    OrbitSimDeployment::rateGroup1.set_RateGroupMemberOut_OutputPort(
        3,
        ComCcsds::comQueue.get_run_InputPort(0)
    );
    OrbitSimDeployment::rateGroup2.set_RateGroupMemberOut_OutputPort(
        0,
        OrbitSimDeployment::cmdSeq.get_schedIn_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_RateGroupMemberOut_OutputPort(
        0,
        CdhCore::health.get_Run_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_RateGroupMemberOut_OutputPort(
        1,
        ComCcsds::commsBufferManager.get_schedIn_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_RateGroupMemberOut_OutputPort(
        2,
        DataProducts::dpBufferManager.get_schedIn_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_RateGroupMemberOut_OutputPort(
        3,
        DataProducts::dpWriter.get_schedIn_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_RateGroupMemberOut_OutputPort(
        4,
        DataProducts::dpMgr.get_schedIn_InputPort(0)
    );
    OrbitSimDeployment::rateGroupDriver.set_CycleOut_OutputPort(
        0,
        OrbitSimDeployment::rateGroup1.get_CycleIn_InputPort(0)
    );
    OrbitSimDeployment::rateGroupDriver.set_CycleOut_OutputPort(
        1,
        OrbitSimDeployment::rateGroup2.get_CycleIn_InputPort(0)
    );
    OrbitSimDeployment::rateGroupDriver.set_CycleOut_OutputPort(
        2,
        OrbitSimDeployment::rateGroup3.get_CycleIn_InputPort(0)
    );
    OrbitSimDeployment::timer.set_CycleOut_OutputPort(
        0,
        OrbitSimDeployment::rateGroupDriver.get_CycleIn_InputPort(0)
    );

    // Telemetry
    CdhCore::cmdDisp.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    CdhCore::health.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    CdhCore::version.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    ComCcsds::comQueue.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    ComCcsds::commsBufferManager.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    ComCcsds::framer.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    ComCcsds::tcDeframer.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    DataProducts::dpBufferManager.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    DataProducts::dpCat.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    DataProducts::dpMgr.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    DataProducts::dpWriter.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    FileHandling::fileDownlink.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    FileHandling::fileManager.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    FileHandling::fileUplink.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    OrbitSimDeployment::cmdSeq.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    OrbitSimDeployment::morseBlinker.set_tlmOut_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    OrbitSimDeployment::rateGroup1.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    OrbitSimDeployment::rateGroup2.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );
    OrbitSimDeployment::systemResources.set_Tlm_OutputPort(
        0,
        CdhCore::tlmSend.get_TlmRecv_InputPort(0)
    );

    // TextEvents
    CdhCore::cmdDisp.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    CdhCore::events.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    CdhCore::fatalAdapter.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    CdhCore::health.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    CdhCore::version.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::apidManager.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::comQueue.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::commsBufferManager.set_textEventOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::fprimeRouter.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::frameAccumulator.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::framer.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    ComCcsds::tcDeframer.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    DataProducts::dpBufferManager.set_textEventOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    DataProducts::dpCat.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    DataProducts::dpMgr.set_textEventOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    DataProducts::dpWriter.set_textEventOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    FileHandling::fileDownlink.set_textEventOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    FileHandling::fileManager.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    FileHandling::fileUplink.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    FileHandling::prmDb.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    OrbitSimDeployment::cmdSeq.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    OrbitSimDeployment::morseBlinker.set_logTextOut_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    OrbitSimDeployment::rateGroup1.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    OrbitSimDeployment::rateGroup2.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );
    OrbitSimDeployment::systemResources.set_LogText_OutputPort(
        0,
        CdhCore::textLogger.get_TextLogger_InputPort(0)
    );

    // Time
    CdhCore::cmdDisp.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    CdhCore::events.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    CdhCore::fatalAdapter.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    CdhCore::health.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    CdhCore::version.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::apidManager.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::comQueue.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::commsBufferManager.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::fprimeRouter.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::frameAccumulator.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::framer.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::spacePacketFramer.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    ComCcsds::tcDeframer.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    DataProducts::dpBufferManager.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    DataProducts::dpCat.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    DataProducts::dpMgr.set_timeGetOut_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    DataProducts::dpWriter.set_timeGetOut_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    FileHandling::fileDownlink.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    FileHandling::fileManager.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    FileHandling::fileUplink.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    FileHandling::prmDb.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    OrbitSimDeployment::cmdSeq.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    OrbitSimDeployment::morseBlinker.set_timeCaller_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    OrbitSimDeployment::rateGroup1.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    OrbitSimDeployment::rateGroup2.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    OrbitSimDeployment::rateGroup3.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );
    OrbitSimDeployment::systemResources.set_Time_OutputPort(
        0,
        OrbitSimDeployment::chronoTime.get_timeGetPort_InputPort(0)
    );

    // Uplink
    ComCcsds::fprimeRouter.set_bufferAllocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferGetCallee_InputPort(0)
    );
    ComCcsds::fprimeRouter.set_bufferDeallocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferSendIn_InputPort(0)
    );
    ComCcsds::fprimeRouter.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::spacePacketDeframer.get_dataReturnIn_InputPort(0)
    );
    ComCcsds::frameAccumulator.set_bufferAllocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferGetCallee_InputPort(0)
    );
    ComCcsds::frameAccumulator.set_bufferDeallocate_OutputPort(
        0,
        ComCcsds::commsBufferManager.get_bufferSendIn_InputPort(0)
    );
    ComCcsds::frameAccumulator.set_dataOut_OutputPort(
        0,
        ComCcsds::tcDeframer.get_dataIn_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_dataOut_OutputPort(
        0,
        ComCcsds::fprimeRouter.get_dataIn_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::tcDeframer.get_dataReturnIn_InputPort(0)
    );
    ComCcsds::spacePacketDeframer.set_validateApidSeqCount_OutputPort(
        0,
        ComCcsds::apidManager.get_validateApidSeqCountIn_InputPort(0)
    );
    ComCcsds::tcDeframer.set_dataOut_OutputPort(
        0,
        ComCcsds::spacePacketDeframer.get_dataIn_InputPort(0)
    );
    ComCcsds::tcDeframer.set_dataReturnOut_OutputPort(
        0,
        ComCcsds::frameAccumulator.get_dataReturnIn_InputPort(0)
    );
  }

  void regCommands() {
    CdhCore::cmdDisp.regCommands();
    CdhCore::events.regCommands();
    CdhCore::health.regCommands();
    CdhCore::version.regCommands();
    DataProducts::dpCat.regCommands();
    DataProducts::dpMgr.regCommands();
    DataProducts::dpWriter.regCommands();
    FileHandling::fileDownlink.regCommands();
    FileHandling::fileManager.regCommands();
    FileHandling::prmDb.regCommands();
    OrbitSimDeployment::cmdSeq.regCommands();
    OrbitSimDeployment::morseBlinker.regCommands();
    OrbitSimDeployment::systemResources.regCommands();
  }

  void readParameters() {
    FileHandling::prmDb.readParamFile();
  }

  void loadParameters() {
    // Nothing to do
  }

  void startTasks(const TopologyState& state) {
    CdhCore::cmdDisp.start(
      static_cast<FwTaskPriorityType>(Priorities::CdhCore_cmdDisp),
      static_cast<Os::Task::ParamType>(StackSizes::CdhCore_cmdDisp),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::CdhCore_cmdDisp)
    );
    CdhCore::events.start(
      static_cast<FwTaskPriorityType>(Priorities::CdhCore_events),
      static_cast<Os::Task::ParamType>(StackSizes::CdhCore_events),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::CdhCore_events)
    );
    CdhCore::tlmSend.start(
      static_cast<FwTaskPriorityType>(Priorities::CdhCore_tlmSend),
      static_cast<Os::Task::ParamType>(StackSizes::CdhCore_tlmSend),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::CdhCore_tlmSend)
    );
    ComCcsds::aggregator.start(
      Os::Task::TASK_PRIORITY_DEFAULT, // Default priority
      static_cast<Os::Task::ParamType>(StackSizes::ComCcsds_aggregator),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ComCcsds_aggregator)
    );
    ComCcsds::comQueue.start(
      static_cast<FwTaskPriorityType>(Priorities::ComCcsds_comQueue),
      static_cast<Os::Task::ParamType>(StackSizes::ComCcsds_comQueue),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ComCcsds_comQueue)
    );
    DataProducts::dpCat.start(
      static_cast<FwTaskPriorityType>(Priorities::DataProducts_dpCat),
      static_cast<Os::Task::ParamType>(StackSizes::DataProducts_dpCat),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::DataProducts_dpCat)
    );
    DataProducts::dpMgr.start(
      static_cast<FwTaskPriorityType>(Priorities::DataProducts_dpMgr),
      static_cast<Os::Task::ParamType>(StackSizes::DataProducts_dpMgr),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::DataProducts_dpMgr)
    );
    DataProducts::dpWriter.start(
      static_cast<FwTaskPriorityType>(Priorities::DataProducts_dpWriter),
      static_cast<Os::Task::ParamType>(StackSizes::DataProducts_dpWriter),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::DataProducts_dpWriter)
    );
    FileHandling::fileDownlink.start(
      static_cast<FwTaskPriorityType>(Priorities::FileHandling_fileDownlink),
      static_cast<Os::Task::ParamType>(StackSizes::FileHandling_fileDownlink),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::FileHandling_fileDownlink)
    );
    FileHandling::fileManager.start(
      static_cast<FwTaskPriorityType>(Priorities::FileHandling_fileManager),
      static_cast<Os::Task::ParamType>(StackSizes::FileHandling_fileManager),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::FileHandling_fileManager)
    );
    FileHandling::fileUplink.start(
      static_cast<FwTaskPriorityType>(Priorities::FileHandling_fileUplink),
      static_cast<Os::Task::ParamType>(StackSizes::FileHandling_fileUplink),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::FileHandling_fileUplink)
    );
    FileHandling::prmDb.start(
      static_cast<FwTaskPriorityType>(Priorities::FileHandling_prmDb),
      static_cast<Os::Task::ParamType>(StackSizes::FileHandling_prmDb),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::FileHandling_prmDb)
    );
    OrbitSimDeployment::cmdSeq.start(
      static_cast<FwTaskPriorityType>(Priorities::OrbitSimDeployment_cmdSeq),
      static_cast<Os::Task::ParamType>(StackSizes::OrbitSimDeployment_cmdSeq),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::OrbitSimDeployment_cmdSeq)
    );
    OrbitSimDeployment::morseBlinker.start(
      static_cast<FwTaskPriorityType>(Priorities::OrbitSimDeployment_morseBlinker),
      static_cast<Os::Task::ParamType>(StackSizes::OrbitSimDeployment_morseBlinker),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::OrbitSimDeployment_morseBlinker)
    );
    OrbitSimDeployment::rateGroup1.start(
      static_cast<FwTaskPriorityType>(Priorities::OrbitSimDeployment_rateGroup1),
      static_cast<Os::Task::ParamType>(StackSizes::OrbitSimDeployment_rateGroup1),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::OrbitSimDeployment_rateGroup1)
    );
    OrbitSimDeployment::rateGroup2.start(
      static_cast<FwTaskPriorityType>(Priorities::OrbitSimDeployment_rateGroup2),
      static_cast<Os::Task::ParamType>(StackSizes::OrbitSimDeployment_rateGroup2),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::OrbitSimDeployment_rateGroup2)
    );
    OrbitSimDeployment::rateGroup3.start(
      static_cast<FwTaskPriorityType>(Priorities::OrbitSimDeployment_rateGroup3),
      static_cast<Os::Task::ParamType>(StackSizes::OrbitSimDeployment_rateGroup3),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::OrbitSimDeployment_rateGroup3)
    );
  }

  void stopTasks(const TopologyState& state) {
    CdhCore::cmdDisp.exit();
    CdhCore::events.exit();
    CdhCore::tlmSend.exit();
    ComCcsds::aggregator.exit();
    ComCcsds::comQueue.exit();
    DataProducts::dpCat.exit();
    DataProducts::dpMgr.exit();
    DataProducts::dpWriter.exit();
    FileHandling::fileDownlink.exit();
    FileHandling::fileManager.exit();
    FileHandling::fileUplink.exit();
    FileHandling::prmDb.exit();
    OrbitSimDeployment::cmdSeq.exit();
    OrbitSimDeployment::morseBlinker.exit();
    OrbitSimDeployment::rateGroup1.exit();
    OrbitSimDeployment::rateGroup2.exit();
    OrbitSimDeployment::rateGroup3.exit();
  }

  void freeThreads(const TopologyState& state) {
    (void) CdhCore::cmdDisp.ActiveComponentBase::join();
    (void) CdhCore::events.ActiveComponentBase::join();
    (void) CdhCore::tlmSend.ActiveComponentBase::join();
    (void) ComCcsds::aggregator.ActiveComponentBase::join();
    (void) ComCcsds::comQueue.ActiveComponentBase::join();
    (void) DataProducts::dpCat.ActiveComponentBase::join();
    (void) DataProducts::dpMgr.ActiveComponentBase::join();
    (void) DataProducts::dpWriter.ActiveComponentBase::join();
    (void) FileHandling::fileDownlink.ActiveComponentBase::join();
    (void) FileHandling::fileManager.ActiveComponentBase::join();
    (void) FileHandling::fileUplink.ActiveComponentBase::join();
    (void) FileHandling::prmDb.ActiveComponentBase::join();
    (void) OrbitSimDeployment::cmdSeq.ActiveComponentBase::join();
    (void) OrbitSimDeployment::morseBlinker.ActiveComponentBase::join();
    (void) OrbitSimDeployment::rateGroup1.ActiveComponentBase::join();
    (void) OrbitSimDeployment::rateGroup2.ActiveComponentBase::join();
    (void) OrbitSimDeployment::rateGroup3.ActiveComponentBase::join();
  }

  void tearDownComponents(const TopologyState& state) {
    ComCcsds::comQueue.cleanup();
    ComCcsds::commsBufferManager.cleanup();
    ComCcsds::frameAccumulator.cleanup();
    DataProducts::dpCat.shutdown();
    DataProducts::dpBufferManager.cleanup();
  }

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  void setup(const TopologyState& state) {
    initComponents(state);
    configComponents(state);
    setBaseIds();
    connectComponents();
    regCommands();
    readParameters();
    loadParameters();
    startTasks(state);
  }

  void teardown(const TopologyState& state) {
    stopTasks(state);
    freeThreads(state);
    tearDownComponents(state);
  }

}
