// ======================================================================
// \title  GpioStatusEnumAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for GpioStatus enum
// ======================================================================

#ifndef Drv_GpioStatusEnumAc_HPP
#define Drv_GpioStatusEnumAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Drv {

  class GpioStatus :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The serial representation type
      typedef U8 SerialType;

      //! The raw enum type
      enum T {
        //! Operation succeeded
        OP_OK = 0,
        //! Pin was never opened
        NOT_OPENED = 1,
        //! Operation not permitted with current configuration
        INVALID_MODE = 2,
        //! An unknown error occurred
        UNKNOWN_ERROR = 3,
      };

      //! For backwards compatibility
      typedef T t;

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE = sizeof(SerialType),
        //! The number of enumerated constants
        NUM_CONSTANTS = 4,
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value of OP_OK)
      GpioStatus()
      {
        this->e = OP_OK;
      }

      //! Constructor (user-provided value)
      GpioStatus(
          const T e1 //!< The raw enum value
      )
      {
        this->e = e1;
      }

      //! Copy constructor
      GpioStatus(
          const GpioStatus& obj //!< The source object
      )
      {
        this->e = obj.e;
      }

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator (object)
      GpioStatus& operator=(
          const GpioStatus& obj //!< The source object
      );

      //! Copy assignment operator (raw enum)
      GpioStatus& operator=(
          T e1 //!< The enum value
      );

      //! Conversion operator
      operator T() const
      {
        return this->e;
      }

      //! Equality operator
      bool operator==(T e1) const
      {
        return this->e == e1;
      }

      //! Inequality operator
      bool operator!=(T e1) const
      {
        return !(*this == e1);
      }

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const GpioStatus& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Check raw enum value for validity
      bool isValid() const;

      //! Serialize raw enum value to SerialType
      Fw::SerializeStatus serializeTo(
          Fw::SerialBufferBase& buffer, //!< The serial buffer
          Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
      ) const;

      //! Deserialize raw enum value from SerialType
      Fw::SerializeStatus deserializeFrom(
          Fw::SerialBufferBase& buffer, //!< The serial buffer
          Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
      );

#if FW_SERIALIZABLE_TO_STRING

      //! Convert enum to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

    public:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The raw enum value
      T e;

  };

}

#endif
