// ======================================================================
// \title  ByteStreamBufferAdapterComponentAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ByteStreamBufferAdapter component base class
// ======================================================================

#include "Drv/ByteStreamBufferAdapter/ByteStreamBufferAdapterComponentAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"
#if FW_ENABLE_TEXT_LOGGING
#include "Fw/Types/String.hpp"
#endif

namespace Drv {

  // ----------------------------------------------------------------------
  // Component initialization
  // ----------------------------------------------------------------------

  void ByteStreamBufferAdapterComponentBase ::
    init(FwEnumStoreType instance)
  {
    // Initialize base class
    Fw::PassiveComponentBase::init(instance);

    // Connect input port bufferIn
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_bufferIn_InputPorts());
      port++
    ) {
      this->m_bufferIn_InputPort[port].init();
      this->m_bufferIn_InputPort[port].addCallComp(
        this,
        m_p_bufferIn_in
      );
      this->m_bufferIn_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_bufferIn_InputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_bufferIn_InputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect input port bufferOutReturn
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_bufferOutReturn_InputPorts());
      port++
    ) {
      this->m_bufferOutReturn_InputPort[port].init();
      this->m_bufferOutReturn_InputPort[port].addCallComp(
        this,
        m_p_bufferOutReturn_in
      );
      this->m_bufferOutReturn_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_bufferOutReturn_InputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_bufferOutReturn_InputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect input port byteStreamDriverReady
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_byteStreamDriverReady_InputPorts());
      port++
    ) {
      this->m_byteStreamDriverReady_InputPort[port].init();
      this->m_byteStreamDriverReady_InputPort[port].addCallComp(
        this,
        m_p_byteStreamDriverReady_in
      );
      this->m_byteStreamDriverReady_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_byteStreamDriverReady_InputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_byteStreamDriverReady_InputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect input port fromByteStreamDriver
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_fromByteStreamDriver_InputPorts());
      port++
    ) {
      this->m_fromByteStreamDriver_InputPort[port].init();
      this->m_fromByteStreamDriver_InputPort[port].addCallComp(
        this,
        m_p_fromByteStreamDriver_in
      );
      this->m_fromByteStreamDriver_InputPort[port].setPortNum(port);

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_fromByteStreamDriver_InputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_fromByteStreamDriver_InputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect output port bufferInReturn
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_bufferInReturn_OutputPorts());
      port++
    ) {
      this->m_bufferInReturn_OutputPort[port].init();

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_bufferInReturn_OutputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_bufferInReturn_OutputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect output port bufferOut
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_bufferOut_OutputPorts());
      port++
    ) {
      this->m_bufferOut_OutputPort[port].init();

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_bufferOut_OutputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_bufferOut_OutputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect output port fromByteStreamDriverReturn
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_fromByteStreamDriverReturn_OutputPorts());
      port++
    ) {
      this->m_fromByteStreamDriverReturn_OutputPort[port].init();

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_fromByteStreamDriverReturn_OutputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_fromByteStreamDriverReturn_OutputPort[port].setObjName(portName.toChar());
#endif
    }

    // Connect output port toByteStreamDriver
    for (
      FwIndexType port = 0;
      port < static_cast<FwIndexType>(this->getNum_toByteStreamDriver_OutputPorts());
      port++
    ) {
      this->m_toByteStreamDriver_OutputPort[port].init();

#if FW_OBJECT_NAMES == 1
      Fw::ObjectName portName;
      portName.format(
        "%s_toByteStreamDriver_OutputPort[%" PRI_FwIndexType "]",
        this->m_objName.toChar(),
        port
      );
      this->m_toByteStreamDriver_OutputPort[port].setObjName(portName.toChar());
#endif
    }
  }

  // ----------------------------------------------------------------------
  // Getters for typed input ports
  // ----------------------------------------------------------------------

  Fw::InputBufferSendPort* ByteStreamBufferAdapterComponentBase ::
    get_bufferIn_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferIn_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_bufferIn_InputPort[portNum];
  }

  Fw::InputBufferSendPort* ByteStreamBufferAdapterComponentBase ::
    get_bufferOutReturn_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferOutReturn_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_bufferOutReturn_InputPort[portNum];
  }

  Drv::InputByteStreamReadyPort* ByteStreamBufferAdapterComponentBase ::
    get_byteStreamDriverReady_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_byteStreamDriverReady_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_byteStreamDriverReady_InputPort[portNum];
  }

  Drv::InputByteStreamDataPort* ByteStreamBufferAdapterComponentBase ::
    get_fromByteStreamDriver_InputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_fromByteStreamDriver_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return &this->m_fromByteStreamDriver_InputPort[portNum];
  }

  // ----------------------------------------------------------------------
  // Connect typed input ports to typed output ports
  // ----------------------------------------------------------------------

  void ByteStreamBufferAdapterComponentBase ::
    set_bufferInReturn_OutputPort(
        FwIndexType portNum,
        Fw::InputBufferSendPort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferInReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_bufferInReturn_OutputPort[portNum].addCallPort(port);
  }

  void ByteStreamBufferAdapterComponentBase ::
    set_bufferOut_OutputPort(
        FwIndexType portNum,
        Fw::InputBufferSendPort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferOut_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_bufferOut_OutputPort[portNum].addCallPort(port);
  }

  void ByteStreamBufferAdapterComponentBase ::
    set_fromByteStreamDriverReturn_OutputPort(
        FwIndexType portNum,
        Fw::InputBufferSendPort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_fromByteStreamDriverReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_fromByteStreamDriverReturn_OutputPort[portNum].addCallPort(port);
  }

  void ByteStreamBufferAdapterComponentBase ::
    set_toByteStreamDriver_OutputPort(
        FwIndexType portNum,
        Drv::InputByteStreamSendPort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_toByteStreamDriver_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_toByteStreamDriver_OutputPort[portNum].addCallPort(port);
  }

#if FW_PORT_SERIALIZATION

  // ----------------------------------------------------------------------
  // Connect serial input ports to typed output ports
  // ----------------------------------------------------------------------

  void ByteStreamBufferAdapterComponentBase ::
    set_bufferInReturn_OutputPort(
        FwIndexType portNum,
        Fw::InputSerializePort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferInReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_bufferInReturn_OutputPort[portNum].registerSerialPort(port);
  }

  void ByteStreamBufferAdapterComponentBase ::
    set_bufferOut_OutputPort(
        FwIndexType portNum,
        Fw::InputSerializePort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferOut_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_bufferOut_OutputPort[portNum].registerSerialPort(port);
  }

  void ByteStreamBufferAdapterComponentBase ::
    set_fromByteStreamDriverReturn_OutputPort(
        FwIndexType portNum,
        Fw::InputSerializePort* port
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_fromByteStreamDriverReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    this->m_fromByteStreamDriverReturn_OutputPort[portNum].registerSerialPort(port);
  }

#endif

  // ----------------------------------------------------------------------
  // Component construction and destruction
  // ----------------------------------------------------------------------

  ByteStreamBufferAdapterComponentBase ::
    ByteStreamBufferAdapterComponentBase(const char* compName) :
      Fw::PassiveComponentBase(compName)
  {

  }

  ByteStreamBufferAdapterComponentBase ::
    ~ByteStreamBufferAdapterComponentBase()
  {

  }

  // ----------------------------------------------------------------------
  // Connection status queries for typed output ports
  // ----------------------------------------------------------------------

  bool ByteStreamBufferAdapterComponentBase ::
    isConnected_bufferInReturn_OutputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferInReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return this->m_bufferInReturn_OutputPort[portNum].isConnected();
  }

  bool ByteStreamBufferAdapterComponentBase ::
    isConnected_bufferOut_OutputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferOut_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return this->m_bufferOut_OutputPort[portNum].isConnected();
  }

  bool ByteStreamBufferAdapterComponentBase ::
    isConnected_fromByteStreamDriverReturn_OutputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_fromByteStreamDriverReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return this->m_fromByteStreamDriverReturn_OutputPort[portNum].isConnected();
  }

  bool ByteStreamBufferAdapterComponentBase ::
    isConnected_toByteStreamDriver_OutputPort(FwIndexType portNum)
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_toByteStreamDriver_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    return this->m_toByteStreamDriver_OutputPort[portNum].isConnected();
  }

  // ----------------------------------------------------------------------
  // Port handler base-class functions for typed input ports
  //
  // Call these functions directly to bypass the corresponding ports
  // ----------------------------------------------------------------------

  void ByteStreamBufferAdapterComponentBase ::
    bufferIn_handlerBase(
        FwIndexType portNum,
        Fw::Buffer& fwBuffer
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferIn_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    // Call handler function
    this->bufferIn_handler(
      portNum,
      fwBuffer
    );
  }

  void ByteStreamBufferAdapterComponentBase ::
    bufferOutReturn_handlerBase(
        FwIndexType portNum,
        Fw::Buffer& fwBuffer
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferOutReturn_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    // Call handler function
    this->bufferOutReturn_handler(
      portNum,
      fwBuffer
    );
  }

  void ByteStreamBufferAdapterComponentBase ::
    byteStreamDriverReady_handlerBase(FwIndexType portNum)
  {
    // Make sure port number is valid
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_byteStreamDriverReady_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    // Call handler function
    this->byteStreamDriverReady_handler(portNum);
  }

  void ByteStreamBufferAdapterComponentBase ::
    fromByteStreamDriver_handlerBase(
        FwIndexType portNum,
        Fw::Buffer& buffer,
        const Drv::ByteStreamStatus& status
    )
  {
    // Make sure port number is valid
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_fromByteStreamDriver_InputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    // Call handler function
    this->fromByteStreamDriver_handler(
      portNum,
      buffer,
      status
    );
  }

  // ----------------------------------------------------------------------
  // Invocation functions for typed output ports
  // ----------------------------------------------------------------------

  void ByteStreamBufferAdapterComponentBase ::
    bufferInReturn_out(
        FwIndexType portNum,
        Fw::Buffer& fwBuffer
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferInReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    FW_ASSERT(
      this->m_bufferInReturn_OutputPort[portNum].isConnected(),
      static_cast<FwAssertArgType>(portNum)
    );
    this->m_bufferInReturn_OutputPort[portNum].invoke(
      fwBuffer
    );
  }

  void ByteStreamBufferAdapterComponentBase ::
    bufferOut_out(
        FwIndexType portNum,
        Fw::Buffer& fwBuffer
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_bufferOut_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    FW_ASSERT(
      this->m_bufferOut_OutputPort[portNum].isConnected(),
      static_cast<FwAssertArgType>(portNum)
    );
    this->m_bufferOut_OutputPort[portNum].invoke(
      fwBuffer
    );
  }

  void ByteStreamBufferAdapterComponentBase ::
    fromByteStreamDriverReturn_out(
        FwIndexType portNum,
        Fw::Buffer& fwBuffer
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_fromByteStreamDriverReturn_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    FW_ASSERT(
      this->m_fromByteStreamDriverReturn_OutputPort[portNum].isConnected(),
      static_cast<FwAssertArgType>(portNum)
    );
    this->m_fromByteStreamDriverReturn_OutputPort[portNum].invoke(
      fwBuffer
    );
  }

  Drv::ByteStreamStatus ByteStreamBufferAdapterComponentBase ::
    toByteStreamDriver_out(
        FwIndexType portNum,
        Fw::Buffer& sendBuffer
    )
  {
    FW_ASSERT(
      (0 <= portNum) && (portNum < this->getNum_toByteStreamDriver_OutputPorts()),
      static_cast<FwAssertArgType>(portNum)
    );

    FW_ASSERT(
      this->m_toByteStreamDriver_OutputPort[portNum].isConnected(),
      static_cast<FwAssertArgType>(portNum)
    );
    return this->m_toByteStreamDriver_OutputPort[portNum].invoke(
      sendBuffer
    );
  }

  // ----------------------------------------------------------------------
  // Calls for messages received on typed input ports
  // ----------------------------------------------------------------------

  void ByteStreamBufferAdapterComponentBase ::
    m_p_bufferIn_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        Fw::Buffer& fwBuffer
    )
  {
    FW_ASSERT(callComp);
    ByteStreamBufferAdapterComponentBase* compPtr = static_cast<ByteStreamBufferAdapterComponentBase*>(callComp);
    compPtr->bufferIn_handlerBase(
      portNum,
      fwBuffer
    );
  }

  void ByteStreamBufferAdapterComponentBase ::
    m_p_bufferOutReturn_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        Fw::Buffer& fwBuffer
    )
  {
    FW_ASSERT(callComp);
    ByteStreamBufferAdapterComponentBase* compPtr = static_cast<ByteStreamBufferAdapterComponentBase*>(callComp);
    compPtr->bufferOutReturn_handlerBase(
      portNum,
      fwBuffer
    );
  }

  void ByteStreamBufferAdapterComponentBase ::
    m_p_byteStreamDriverReady_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum
    )
  {
    FW_ASSERT(callComp);
    ByteStreamBufferAdapterComponentBase* compPtr = static_cast<ByteStreamBufferAdapterComponentBase*>(callComp);
    compPtr->byteStreamDriverReady_handlerBase(portNum);
  }

  void ByteStreamBufferAdapterComponentBase ::
    m_p_fromByteStreamDriver_in(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        Fw::Buffer& buffer,
        const Drv::ByteStreamStatus& status
    )
  {
    FW_ASSERT(callComp);
    ByteStreamBufferAdapterComponentBase* compPtr = static_cast<ByteStreamBufferAdapterComponentBase*>(callComp);
    compPtr->fromByteStreamDriver_handlerBase(
      portNum,
      buffer,
      status
    );
  }

}
