// ======================================================================
// \title  DpWrittenPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DpWritten port
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Svc/DpPorts/DpWrittenPortAc.hpp"

namespace Svc {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class DpWrittenPortBuffer : public Fw::LinearBufferBase {

      public:

        Fw::Serializable::SizeType getCapacity() const {
          return InputDpWrittenPort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputDpWrittenPort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputDpWrittenPort ::
    InputDpWrittenPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputDpWrittenPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputDpWrittenPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputDpWrittenPort ::
    invoke(
        const Fw::StringBase& fileName,
        FwDpPriorityType priority,
        FwSizeType size
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, fileName, priority, size);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputDpWrittenPort ::
    invokeSerial(Fw::LinearBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    char __fprime_ac_fileName_buffer[Fw::StringBase::BUFFER_SIZE(200)];
    Fw::ExternalString fileName(__fprime_ac_fileName_buffer, sizeof __fprime_ac_fileName_buffer);
    _status = _buffer.deserializeTo(fileName);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    FwDpPriorityType priority;
    _status = _buffer.deserializeTo(priority);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    FwSizeType size;
    _status = _buffer.deserializeTo(size);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, fileName, priority, size);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputDpWrittenPort ::
    OutputDpWrittenPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputDpWrittenPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputDpWrittenPort ::
    addCallPort(InputDpWrittenPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputDpWrittenPort ::
    invoke(
        const Fw::StringBase& fileName,
        FwDpPriorityType priority,
        FwSizeType size
    ) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(fileName, priority, size);
    }
    else {
      Fw::SerializeStatus _status;
      DpWrittenPortBuffer _buffer;

      _status = _buffer.serializeFrom(fileName);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serializeFrom(priority);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serializeFrom(size);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(fileName, priority, size);
#endif
  }

}
