// ======================================================================
// \title  FooterSerializableAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for Footer struct
// ======================================================================

#ifndef Svc_Fpy_FooterSerializableAc_HPP
#define Svc_Fpy_FooterSerializableAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Svc {

  namespace Fpy {

    class Footer :
      public Fw::Serializable
    {

      public:

        // ----------------------------------------------------------------------
        // Constants
        // ----------------------------------------------------------------------

        enum {
          //! The size of the serial representation
          SERIALIZED_SIZE =
            sizeof(U32)
        };

      public:

        // ----------------------------------------------------------------------
        // Constructors
        // ----------------------------------------------------------------------

        //! Constructor (default value)
        Footer();

        //! Member constructor
        Footer(U32 crc);

        //! Copy constructor
        Footer(
            const Footer& obj //!< The source object
        );

      public:

        // ----------------------------------------------------------------------
        // Operators
        // ----------------------------------------------------------------------

        //! Copy assignment operator
        Footer& operator=(
            const Footer& obj //!< The source object
        );

        //! Equality operator
        bool operator==(
            const Footer& obj //!< The other object
        ) const;

        //! Inequality operator
        bool operator!=(
            const Footer& obj //!< The other object
        ) const;

#ifdef BUILD_UT

        //! Ostream operator
        friend std::ostream& operator<<(
            std::ostream& os, //!< The ostream
            const Footer& obj //!< The object
        );

#endif

      public:

        // ----------------------------------------------------------------------
        // Member functions
        // ----------------------------------------------------------------------

        //! Serialization
        Fw::SerializeStatus serializeTo(
            Fw::SerialBufferBase& buffer, //!< The serial buffer
            Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
        ) const;

        //! Deserialization
        Fw::SerializeStatus deserializeFrom(
            Fw::SerialBufferBase& buffer, //!< The serial buffer
            Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
        );

        //! Get the dynamic serialized size of the struct
        FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

        //! Convert struct to string
        void toString(
            Fw::StringBase& sb //!< The StringBase object to hold the result
        ) const;

#endif

        // ----------------------------------------------------------------------
        // Getter functions
        // ----------------------------------------------------------------------

        //! Get member crc
        U32 get_crc() const
        {
          return this->m_crc;
        }

        // ----------------------------------------------------------------------
        // Setter functions
        // ----------------------------------------------------------------------

        //! Set all members
        void set(U32 crc);

        //! Set member crc
        void set_crc(U32 crc);

      protected:

        // ----------------------------------------------------------------------
        // Member variables
        // ----------------------------------------------------------------------

        U32 m_crc;

    };

  }

}

#endif
