// ======================================================================
// \title  FpySequencer_WaitAbsDirectiveSerializableAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FpySequencer_WaitAbsDirective struct
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "Svc/FpySequencer/FpySequencer_WaitAbsDirectiveSerializableAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Constructors
  // ----------------------------------------------------------------------

  FpySequencer_WaitAbsDirective ::
    FpySequencer_WaitAbsDirective() :
      Serializable(),
      m__empty()
  {

  }

  FpySequencer_WaitAbsDirective ::
    FpySequencer_WaitAbsDirective(U8 _empty) :
      Serializable(),
      m__empty(_empty)
  {

  }

  FpySequencer_WaitAbsDirective ::
    FpySequencer_WaitAbsDirective(const FpySequencer_WaitAbsDirective& obj) :
      Serializable(),
      m__empty(obj.m__empty)
  {

  }

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  FpySequencer_WaitAbsDirective& FpySequencer_WaitAbsDirective ::
    operator=(const FpySequencer_WaitAbsDirective& obj)
  {
    if (this == &obj) {
      return *this;
    }

    set(obj.m__empty);
    return *this;
  }

  bool FpySequencer_WaitAbsDirective ::
    operator==(const FpySequencer_WaitAbsDirective& obj) const
  {
    return (this->m__empty == obj.m__empty);
  }

  bool FpySequencer_WaitAbsDirective ::
    operator!=(const FpySequencer_WaitAbsDirective& obj) const
  {
    return !(*this == obj);
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const FpySequencer_WaitAbsDirective& obj) {
    Fw::String s;
    obj.toString(s);
    os << s.toChar();
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  Fw::SerializeStatus FpySequencer_WaitAbsDirective ::
    serializeTo(
        Fw::SerialBufferBase& buffer,
        Fw::Endianness mode
    ) const
  {
    Fw::SerializeStatus status;

    status = buffer.serializeFrom(this->m__empty, mode);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

  Fw::SerializeStatus FpySequencer_WaitAbsDirective ::
    deserializeFrom(
        Fw::SerialBufferBase& buffer,
        Fw::Endianness mode
    )
  {
    Fw::SerializeStatus status;

    status = buffer.deserializeTo(this->m__empty, mode);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

  FwSizeType FpySequencer_WaitAbsDirective ::
    serializedSize() const
  {
    FwSizeType size = 0;
    size += sizeof(U8);
    return size;
  }

#if FW_SERIALIZABLE_TO_STRING

  void FpySequencer_WaitAbsDirective ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String tmp;
    sb = "( ";

    // Format _empty
    sb += "_empty = ";
    tmp.format("%" PRIu8 "", this->m__empty);
    sb += tmp;
    sb += " )";
  }

#endif

  // ----------------------------------------------------------------------
  // Setter functions
  // ----------------------------------------------------------------------

  void FpySequencer_WaitAbsDirective ::
    set(U8 _empty)
  {
    this->m__empty = _empty;
  }

  void FpySequencer_WaitAbsDirective ::
    set__empty(U8 _empty)
  {
    this->m__empty = _empty;
  }

}
