// ======================================================================
// \title  FpySequencer_StoreDirectiveSerializableAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FpySequencer_StoreDirective struct
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "Svc/FpySequencer/FpySequencer_StoreDirectiveSerializableAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Constructors
  // ----------------------------------------------------------------------

  FpySequencer_StoreDirective ::
    FpySequencer_StoreDirective() :
      Serializable(),
      m_size()
  {

  }

  FpySequencer_StoreDirective ::
    FpySequencer_StoreDirective(Svc::Fpy::StackSizeType size) :
      Serializable(),
      m_size(size)
  {

  }

  FpySequencer_StoreDirective ::
    FpySequencer_StoreDirective(const FpySequencer_StoreDirective& obj) :
      Serializable(),
      m_size(obj.m_size)
  {

  }

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  FpySequencer_StoreDirective& FpySequencer_StoreDirective ::
    operator=(const FpySequencer_StoreDirective& obj)
  {
    if (this == &obj) {
      return *this;
    }

    set(obj.m_size);
    return *this;
  }

  bool FpySequencer_StoreDirective ::
    operator==(const FpySequencer_StoreDirective& obj) const
  {
    return (this->m_size == obj.m_size);
  }

  bool FpySequencer_StoreDirective ::
    operator!=(const FpySequencer_StoreDirective& obj) const
  {
    return !(*this == obj);
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const FpySequencer_StoreDirective& obj) {
    Fw::String s;
    obj.toString(s);
    os << s.toChar();
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  Fw::SerializeStatus FpySequencer_StoreDirective ::
    serializeTo(
        Fw::SerialBufferBase& buffer,
        Fw::Endianness mode
    ) const
  {
    Fw::SerializeStatus status;

    status = buffer.serializeFrom(this->m_size, mode);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

  Fw::SerializeStatus FpySequencer_StoreDirective ::
    deserializeFrom(
        Fw::SerialBufferBase& buffer,
        Fw::Endianness mode
    )
  {
    Fw::SerializeStatus status;

    status = buffer.deserializeTo(this->m_size, mode);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

  FwSizeType FpySequencer_StoreDirective ::
    serializedSize() const
  {
    FwSizeType size = 0;
    size += sizeof(Svc::Fpy::StackSizeType);
    return size;
  }

#if FW_SERIALIZABLE_TO_STRING

  void FpySequencer_StoreDirective ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String tmp;
    sb = "( ";

    // Format size
    sb += "size = ";
    tmp.format("%" PRIu32 "", this->m_size);
    sb += tmp;
    sb += " )";
  }

#endif

  // ----------------------------------------------------------------------
  // Setter functions
  // ----------------------------------------------------------------------

  void FpySequencer_StoreDirective ::
    set(Svc::Fpy::StackSizeType size)
  {
    this->m_size = size;
  }

  void FpySequencer_StoreDirective ::
    set_size(Svc::Fpy::StackSizeType size)
  {
    this->m_size = size;
  }

}
