// ======================================================================
// \title  SendFileResponseSerializableAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for SendFileResponse struct
// ======================================================================

#ifndef Svc_SendFileResponseSerializableAc_HPP
#define Svc_SendFileResponseSerializableAc_HPP

#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"
#include "Svc/FileDownlinkPorts/SendFileStatusEnumAc.hpp"

namespace Svc {

  //! Send file response struct
  class SendFileResponse :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE =
          Svc::SendFileStatus::SERIALIZED_SIZE +
          sizeof(U32)
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value)
      SendFileResponse();

      //! Member constructor
      SendFileResponse(
          Svc::SendFileStatus::T status,
          U32 context
      );

      //! Copy constructor
      SendFileResponse(
          const SendFileResponse& obj //!< The source object
      );

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator
      SendFileResponse& operator=(
          const SendFileResponse& obj //!< The source object
      );

      //! Equality operator
      bool operator==(
          const SendFileResponse& obj //!< The other object
      ) const;

      //! Inequality operator
      bool operator!=(
          const SendFileResponse& obj //!< The other object
      ) const;

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const SendFileResponse& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Serialization
      Fw::SerializeStatus serializeTo(
          Fw::SerialBufferBase& buffer, //!< The serial buffer
          Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
      ) const;

      //! Deserialization
      Fw::SerializeStatus deserializeFrom(
          Fw::SerialBufferBase& buffer, //!< The serial buffer
          Fw::Endianness mode = Fw::Endianness::BIG //!< Endianness of serialized buffer
      );

      //! Get the dynamic serialized size of the struct
      FwSizeType serializedSize() const;

#if FW_SERIALIZABLE_TO_STRING

      //! Convert struct to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

      // ----------------------------------------------------------------------
      // Getter functions
      // ----------------------------------------------------------------------

      //! Get member status
      Svc::SendFileStatus::T get_status() const
      {
        return this->m_status.e;
      }

      //! Get member context
      U32 get_context() const
      {
        return this->m_context;
      }

      // ----------------------------------------------------------------------
      // Setter functions
      // ----------------------------------------------------------------------

      //! Set all members
      void set(
          Svc::SendFileStatus::T status,
          U32 context
      );

      //! Set member status
      void set_status(Svc::SendFileStatus::T status);

      //! Set member context
      void set_context(U32 context);

    protected:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      Svc::SendFileStatus m_status;
      U32 m_context;

  };

}

#endif
