// ======================================================================
// \title  ByteStreamDataPortAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ByteStreamData port
// ======================================================================

#include "Drv/ByteStreamDriverModel/ByteStreamDataPortAc.hpp"
#include "Fw/Types/Assert.hpp"
#include "Fw/Types/ExternalString.hpp"

namespace Drv {

  namespace {

    // ----------------------------------------------------------------------
    // Port buffer class
    // ----------------------------------------------------------------------

    class ByteStreamDataPortBuffer : public Fw::LinearBufferBase {

      public:

        Fw::Serializable::SizeType getCapacity() const {
          return InputByteStreamDataPort::SERIALIZED_SIZE;
        }

        U8* getBuffAddr() {
          return m_buff;
        }

        const U8* getBuffAddr() const {
          return m_buff;
        }

      private:

        U8 m_buff[InputByteStreamDataPort::SERIALIZED_SIZE];

    };

  }

  // ----------------------------------------------------------------------
  // Input Port Member functions
  // ----------------------------------------------------------------------

  InputByteStreamDataPort ::
    InputByteStreamDataPort() :
      Fw::InputPortBase(),
      m_func(nullptr)
  {

  }

  void InputByteStreamDataPort ::
    init()
  {
    Fw::InputPortBase::init();
  }

  void InputByteStreamDataPort ::
    addCallComp(
        Fw::PassiveComponentBase* callComp,
        CompFuncPtr funcPtr
    )
  {
    FW_ASSERT(callComp != nullptr);
    FW_ASSERT(funcPtr != nullptr);

    this->m_comp = callComp;
    this->m_func = funcPtr;
    this->m_connObj = callComp;
  }

  void InputByteStreamDataPort ::
    invoke(
        Fw::Buffer& buffer,
        const Drv::ByteStreamStatus& status
    )
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    return this->m_func(this->m_comp, this->m_portNum, buffer, status);
  }

#if FW_PORT_SERIALIZATION == 1

  Fw::SerializeStatus InputByteStreamDataPort ::
    invokeSerial(Fw::LinearBufferBase& _buffer)
  {
    Fw::SerializeStatus _status;

#if FW_PORT_TRACING == 1
    this->trace();
#endif

    FW_ASSERT(this->m_comp != nullptr);
    FW_ASSERT(this->m_func != nullptr);

    Fw::Buffer buffer;
    _status = _buffer.deserializeTo(buffer);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    Drv::ByteStreamStatus status;
    _status = _buffer.deserializeTo(status);
    if (_status != Fw::FW_SERIALIZE_OK) {
      return _status;
    }

    this->m_func(this->m_comp, this->m_portNum, buffer, status);

    return Fw::FW_SERIALIZE_OK;
  }

#endif

  // ----------------------------------------------------------------------
  // Output Port Member functions
  // ----------------------------------------------------------------------

  OutputByteStreamDataPort ::
    OutputByteStreamDataPort() :
      Fw::OutputPortBase(),
      m_port(nullptr)
  {

  }

  void OutputByteStreamDataPort ::
    init()
  {
    Fw::OutputPortBase::init();
  }

  void OutputByteStreamDataPort ::
    addCallPort(InputByteStreamDataPort* callPort)
  {
    FW_ASSERT(callPort != nullptr);

    this->m_port = callPort;
    this->m_connObj = callPort;

#if FW_PORT_SERIALIZATION == 1
    this->m_serPort = nullptr;
#endif
  }

  void OutputByteStreamDataPort ::
    invoke(
        Fw::Buffer& buffer,
        const Drv::ByteStreamStatus& status
    ) const
  {
#if FW_PORT_TRACING == 1
    this->trace();
#endif

#if FW_PORT_SERIALIZATION
    FW_ASSERT((this->m_port != nullptr) || (this->m_serPort != nullptr));

    if (this->m_port != nullptr) {
      this->m_port->invoke(buffer, status);
    }
    else {
      Fw::SerializeStatus _status;
      ByteStreamDataPortBuffer _buffer;

      _status = _buffer.serializeFrom(buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = _buffer.serializeFrom(status);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));

      _status = this->m_serPort->invokeSerial(_buffer);
      FW_ASSERT(_status == Fw::FW_SERIALIZE_OK, static_cast<FwAssertArgType>(_status));
    }
#else
    FW_ASSERT(this->m_port != nullptr);
    this->m_port->invoke(buffer, status);
#endif
  }

}
