// ======================================================================
// \title  ByteStreamReadyPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for ByteStreamReady port
// ======================================================================

#ifndef Drv_ByteStreamReadyPortAc_HPP
#define Drv_ByteStreamReadyPortAc_HPP

#include <cstdio>
#include <cstring>

#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/FPrimeBasicTypes.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace Drv {

  //! Input ByteStreamReady port
  //! Signal indicating the driver is ready to send and received data
  class InputByteStreamReadyPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE = 0
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef void (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputByteStreamReadyPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      void invoke();

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::LinearBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output ByteStreamReady port
  //! Signal indicating the driver is ready to send and received data
  class OutputByteStreamReadyPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputByteStreamReadyPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputByteStreamReadyPort* callPort //!< The input port
      );

      //! Invoke a port interface
      void invoke() const;

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputByteStreamReadyPort* m_port;

  };

}

#endif
